(custom-put 'extensions 'custom-loads '("wid-edit"))
(custom-put 'custom-buffer 'custom-loads '("cus-edit"))
(custom-put 'custom-faces 'custom-loads '("cus-edit"))
(custom-put 'widgets 'custom-loads '("wid-browse" "wid-edit"))
(custom-put 'environment 'custom-loads '("cus-edit"))
(custom-put 'custom-menu 'custom-loads '("cus-edit"))
(custom-put 'internal 'custom-loads '("cus-edit"))
(custom-put 'hypermedia 'custom-loads '("wid-edit"))
(custom-put 'applications 'custom-loads '("cus-edit"))
(custom-put 'help 'custom-loads '("cus-edit"))
(custom-put 'widget-browse 'custom-loads '("wid-browse"))
(custom-put 'customize 'custom-loads '("wid-edit" "cus-edit" "cus-face"))
(custom-put 'custom-browse 'custom-loads '("cus-edit"))
(custom-put 'abbrev 'custom-loads '("cus-edit"))
(custom-put 'programming 'custom-loads '("cus-edit"))
(custom-put 'files 'custom-loads '("cus-edit"))
(custom-put 'external 'custom-loads '("cus-edit"))
(custom-put 'development 'custom-loads '("cus-edit"))
(custom-put 'languages 'custom-loads '("cus-edit"))
(custom-put 'faces 'custom-loads '("cus-edit" "wid-edit"))
(custom-put 'emacs 'custom-loads '("cus-edit"))
(custom-put 'processes 'custom-loads '("cus-edit"))
(custom-put 'wp 'custom-loads '("cus-edit"))
(custom-put 'editing 'custom-loads '("cus-edit"))
(custom-put 'i18n 'custom-loads '("cus-edit"))
