(custom-put 'extensions 'custom-loads '("page-ext" "time-stamp"))
(custom-put 'change-log 'custom-loads '("add-log"))
(custom-put 'filladapt 'custom-loads '("filladapt"))
(custom-put 'copyright 'custom-loads '("upd-copyr"))
(custom-put 'recent-files-menu 'custom-loads '("recent-files"))
(custom-put 'mouse 'custom-loads '("avoid"))
(custom-put 'tex 'custom-loads '("texnfo-tex"))
(custom-put 'tar 'custom-loads '("tar-mode"))
(custom-put 'etags 'custom-loads '("etags"))
(custom-put 'igrep 'custom-loads '("igrep"))
(custom-put 'menu 'custom-loads '("recent-files"))
(custom-put 'minibuffer 'custom-loads '("icomplete"))
(custom-put 'environment 'custom-loads '("gnuserv"))
(custom-put 'texinfo 'custom-loads '("texnfo-tex"))
(custom-put 'terminals 'custom-loads '("gnuserv"))
(custom-put 'auto-save 'custom-loads '("auto-save"))
(custom-put 'ispell 'custom-loads '("ispell"))
(custom-put 'mail 'custom-loads '("feedmail" "metamail" "supercite"))
(custom-put 'ps-print-face 'custom-loads '("ps-print"))
(custom-put 'crypt 'custom-loads '("crypt"))
(custom-put 'object 'custom-loads '("gopher"))
(custom-put 'man 'custom-loads '("man"))
(custom-put 'lpr 'custom-loads '("lpr"))
(custom-put 'ps-print-header 'custom-loads '("ps-print"))
(custom-put 'docs 'custom-loads '("hyper-apropos" "info" "makeinfo"))
(custom-put 'completion 'custom-loads '("completion"))
(custom-put 'tools 'custom-loads '("add-log" "autoinsert" "compile" "diff" "etags" "func-menu" "generic-sc" "hyper-apropos" "rcompile"))
(custom-put 'recent-files 'custom-loads '("recent-files"))
(custom-put 'display-time-balloon 'custom-loads '("time"))
(custom-put 'dabbrev 'custom-loads '("dabbrev"))
(custom-put 'display-time 'custom-loads '("time"))
(custom-put 'hypermedia 'custom-loads '("gopher" "metamail"))
(custom-put 'save-place 'custom-loads '("saveplace"))
(custom-put 'lisp 'custom-loads '("func-menu" "hyper-apropos"))
(custom-put 'jka-compr 'custom-loads '("jka-compr"))
(custom-put 'diff 'custom-loads '("diff"))
(custom-put 'supercite-cite 'custom-loads '("supercite"))
(custom-put 'applications 'custom-loads '("time"))
(custom-put 'paren-matching 'custom-loads '("paren"))
(custom-put 'time-stamp 'custom-loads '("time-stamp"))
(custom-put 'avoid 'custom-loads '("avoid"))
(custom-put 'help 'custom-loads '("hyper-apropos" "info" "man"))
(custom-put 'supercite 'custom-loads '("supercite"))
(custom-put 'generic-sc 'custom-loads '("generic-sc"))
(custom-put 'local 'custom-loads '("gopher"))
(custom-put 'keyboard 'custom-loads '("pending-del"))
(custom-put 'data 'custom-loads '("auto-save" "jka-compr" "saveplace" "tar-mode" "time-stamp"))
(custom-put 'ps-print 'custom-loads '("ps-print"))
(custom-put 'compression 'custom-loads '("jka-compr"))
(custom-put 'comm 'custom-loads '("gopher"))
(custom-put 'ps-print-font 'custom-loads '("ps-print"))
(custom-put 'frames 'custom-loads '("balloon-help" "desktop"))
(custom-put 'supercite-attr 'custom-loads '("supercite"))
(custom-put 'bookmarks 'custom-loads '("bookmark"))
(custom-put 'desktop 'custom-loads '("desktop"))
(custom-put 'abbrev 'custom-loads '("dabbrev"))
(custom-put 'remote-compile 'custom-loads '("rcompile"))
(custom-put 'programming 'custom-loads '("compile"))
(custom-put 'metamail 'custom-loads '("metamail"))
(custom-put 'icomplete 'custom-loads '("icomplete"))
(custom-put 'compilation 'custom-loads '("compile"))
(custom-put 'makeinfo 'custom-loads '("makeinfo"))
(custom-put 'fume 'custom-loads '("func-menu"))
(custom-put 'auto-insert 'custom-loads '("autoinsert"))
(custom-put 'files 'custom-loads '("recent-files"))
(custom-put 'fast-lock 'custom-loads '("fast-lock"))
(custom-put 'gnuserv 'custom-loads '("gnuserv"))
(custom-put 'ps-print-horizontal 'custom-loads '("ps-print"))
(custom-put 'maint 'custom-loads '("add-log" "upd-copyr"))
(custom-put 'fill 'custom-loads '("filladapt"))
(custom-put 'balloon-help 'custom-loads '("balloon-help"))
(custom-put 'supercite-hooks 'custom-loads '("supercite"))
(custom-put 'texinfo-tex 'custom-loads '("texnfo-tex"))
(custom-put 'faces 'custom-loads '("fast-lock" "hyper-apropos" "ps-print"))
(custom-put 'pages 'custom-loads '("page-ext"))
(custom-put 'supercite-frames 'custom-loads '("supercite"))
(custom-put 'feedmail 'custom-loads '("feedmail"))
(custom-put 'processes 'custom-loads '("compile" "gnuserv" "igrep" "ispell" "metamail" "rcompile"))
(custom-put 'news 'custom-loads '("supercite"))
(custom-put 'hyper-apropos 'custom-loads '("hyper-apropos"))
(custom-put 'wp 'custom-loads '("lpr" "ps-print"))
(custom-put 'ps-print-vertical 'custom-loads '("ps-print"))
(custom-put 'gopher 'custom-loads '("gopher"))
(custom-put 'editing 'custom-loads '("bookmark"))
(custom-put 'matching 'custom-loads '("paren" "completion" "hyper-apropos"))
(custom-put 'ps-print-color 'custom-loads '("ps-print"))
(custom-put 'info 'custom-loads '("info"))
(custom-put 'unix 'custom-loads '("tar-mode"))
(custom-put 'c 'custom-loads '("func-menu"))
