(put 'extensions 'custom-loads '("page-ext" "time-stamp"))
(put 'change-log 'custom-loads '("add-log"))
(put 'filladapt 'custom-loads '("filladapt"))
(put 'copyright 'custom-loads '("upd-copyr"))
(put 'eldoc 'custom-loads '())
(put 'recent-files-menu 'custom-loads '("recent-files"))
(put 'execute 'custom-loads '())
(put 'mouse 'custom-loads '("avoid"))
(put 'mail-abbrevs 'custom-loads '())
(put 'tex 'custom-loads '("texnfo-tex"))
(put 'etags 'custom-loads '("etags"))
(put 'limits 'custom-loads '())
(put 'igrep 'custom-loads '("igrep"))
(put 'minibuffer 'custom-loads '())
(put 'environment 'custom-loads '("gnuserv"))
(put 'sound 'custom-loads '())
(put 'holidays 'custom-loads '())
(put 'texinfo 'custom-loads '("texnfo-tex"))
(put 'terminals 'custom-loads '("gnuserv"))
(put 'auto-save 'custom-loads '("auto-save"))
(put 'ispell 'custom-loads '("ispell"))
(put 'mail 'custom-loads '("feedmail" "metamail" "supercite"))
(put 'fortran-indent 'custom-loads '())
(put 'ps-print-face 'custom-loads '("ps-print"))
(put 'crypt 'custom-loads '("crypt"))
(put 'object 'custom-loads '("gopher"))
(put 'man 'custom-loads '("man"))
(put 'lpr 'custom-loads '("lpr"))
(put 'message-headers 'custom-loads '())
(put 'ps-print-header 'custom-loads '("ps-print"))
(put 'docs 'custom-loads '("hyper-apropos" "makeinfo"))
(put 'completion 'custom-loads '("completion"))
(put 'tools 'custom-loads '("add-log" "diff" "etags" "func-menu" "generic-sc" "hyper-apropos" "rcompile"))
(put 'recent-files 'custom-loads '("recent-files"))
(put 'editing-basics 'custom-loads '())
(put 'display-time-balloon 'custom-loads '("time"))
(put 'internal 'custom-loads '())
(put 'calendar 'custom-loads '())
(put 'dabbrev 'custom-loads '("dabbrev"))
(put 'help-appearance 'custom-loads '())
(put 'display-time 'custom-loads '("time"))
(put 'hypermedia 'custom-loads '("gopher" "metamail"))
(put 'save-place 'custom-loads '("saveplace"))
(put 'lisp 'custom-loads '("hyper-apropos"))
(put 'jka-compr 'custom-loads '("jka-compr"))
(put 'diff 'custom-loads '("diff"))
(put 'supercite-cite 'custom-loads '("supercite"))
(put 'paren-matching 'custom-loads '("paren"))
(put 'time-stamp 'custom-loads '("time-stamp"))
(put 'avoid 'custom-loads '("avoid"))
(put 'help 'custom-loads '("hyper-apropos" "info" "man"))
(put 'supercite 'custom-loads '("supercite"))
(put 'generic-sc 'custom-loads '("generic-sc"))
(put 'local 'custom-loads '("gopher"))
(put 'keyboard 'custom-loads '())
(put 'minubuffer 'custom-loads '())
(put 'hyper-apropos-faces 'custom-loads '("hyper-apropos"))
(put 'message-sending 'custom-loads '())
(put 'data 'custom-loads '("auto-save" "jka-compr" "recent-files" "saveplace" "time-stamp"))
(put 'ps-print 'custom-loads '("ps-print"))
(put 'ps-print-font 'custom-loads '("ps-print"))
(put 'backup 'custom-loads '())
(put 'frames 'custom-loads '("balloon-help" "desktop"))
(put 'customize 'custom-loads '())
(put 'supercite-attr 'custom-loads '("supercite"))
(put 'desktop 'custom-loads '("desktop"))
(put 'abbrev 'custom-loads '("dabbrev"))
(put 'remote-compile 'custom-loads '("rcompile"))
(put 'programming 'custom-loads '("compile"))
(put 'metamail 'custom-loads '("metamail"))
(put 'toolbar 'custom-loads '())
(put 'compilation 'custom-loads '("compile"))
(put 'dired 'custom-loads '())
(put 'makeinfo 'custom-loads '("makeinfo"))
(put 'fume 'custom-loads '("func-menu"))
(put 'killing 'custom-loads '())
(put 'paren-blinking 'custom-loads '())
(put 'find-file 'custom-loads '())
(put 'fast-lock 'custom-loads '("fast-lock"))
(put 'gnuserv 'custom-loads '("gnuserv"))
(put 'ps-print-horizontal 'custom-loads '("ps-print"))
(put 'maint 'custom-loads '("add-log" "upd-copyr"))
(put 'fill-comments 'custom-loads '())
(put 'message-mail 'custom-loads '())
(put 'windows 'custom-loads '())
(put 'message-various 'custom-loads '())
(put 'resize-minibuffer 'custom-loads '())
(put 'fill 'custom-loads '("filladapt"))
(put 'balloon-help 'custom-loads '("balloon-help"))
(put 'debug 'custom-loads '())
(put 'supercite-hooks 'custom-loads '("supercite"))
(put 'display 'custom-loads '())
(put 'texinfo-tex 'custom-loads '("texnfo-tex"))
(put 'faces 'custom-loads '("fast-lock" "ps-print"))
(put 'pages 'custom-loads '("page-ext"))
(put 'diary 'custom-loads '())
(put 'supercite-frames 'custom-loads '("supercite"))
(put 'browse-url 'custom-loads '())
(put 'feedmail 'custom-loads '("feedmail"))
(put 'processes 'custom-loads '("gnuserv" "ispell" "metamail" "rcompile"))
(put 'news 'custom-loads '("supercite"))
(put 'message-insertion 'custom-loads '())
(put 'hyper-apropos 'custom-loads '("hyper-apropos"))
(put 'wp 'custom-loads '("lpr" "ps-print"))
(put 'vc 'custom-loads '())
(put 'ps-print-vertical 'custom-loads '("ps-print"))
(put 'alloc 'custom-loads '())
(put 'isearch 'custom-loads '())
(put 'gopher 'custom-loads '("gopher"))
(put 'modeline 'custom-loads '())
(put 'processes-basics 'custom-loads '())
(put 'editing 'custom-loads '())
(put 'matching 'custom-loads '("completion" "hyper-apropos"))
(put 'ps-print-color 'custom-loads '("ps-print"))
(put 'info 'custom-loads '("info"))
(put 'undo 'custom-loads '())
(put 'x 'custom-loads '())
