(custom-put 'holidays 'custom-loads '("calendar"))
(custom-put 'calendar 'custom-loads '("calendar"))
(custom-put 'local 'custom-loads '("calendar"))
(custom-put 'diary 'custom-loads '("calendar"))
(custom-put 'appt 'custom-loads '("appt"))
