@c $Id: tm-ew=en.texi,v 1.1.1.1 1996/12/18 22:43:52 steve Exp $

@node encoded-word, customize, tm-edit, Top
@comment  node-name,  next,  previous,  up
@chapter encoded-word
@cindex encoded-word
@cindex non-ASCII field
@cindex message header

tm has some functions about encoded-word defined in RFC 1522.

@menu
* encoded-word decoding:: decode
* encoded-word encoding:: encode
* encoded-word utility::
@end menu


@node encoded-word encoding, encoded-word utility, encoded-word, encoded-word
@comment  node-name,  next,  previous,  up
@section encoded-word encoding

@deffn{Command} mime/encode-message-header

It encodes non-ASCII characters in message header of current buffer.
@end deffn


@deffn{Function} mime/encode-field str

It encodes @var{str} as a field.
@end deffn


@deffn{Function} mime-eword/encode-string str &optional column mode

It encodes @var{str}.

@var{column} specifies start column. Default value is 0.

@var{mode} specifies where @var{str} is in. Available values are
@code{text}, @code{comment}, @code{phrase}. Default value is
@code{phrase}.
@end deffn


@node encoded-word utility,  , encoded-word encoding, encoded-word
@comment  node-name,  next,  previous,  up
@section encoded-word utility

@deffn{Function} mime/exist-encoded-word-in-subject

If there are encoded-words in Subject: field in current buffer,
it returns field-body of the Subject: field.
@end deffn
