@c $Id: tm-edit-en.texi,v 1.1.1.1 1996/12/18 22:43:52 steve Exp $

@node tm-edit, encoded-word, tm-view, Top
@comment  node-name,  next,  previous,  up
@chapter tm-edit
@cindex tm-edit

tm-edit is a general MIME viewer for GNU Emacs.

tm-edit is based on mime.el by UMEDA Masanobu
<umerin@@mse.kyutech.ac.jp>, who is famous as the author of GNUS.
tm-edit expands following points from mime.el:

@itemize @bullet
@item based on RFC 1521/1522
@item Content-Disposition field (RFC 1806) supports
@item multi-part in multi-part
@item PGP
@item strength automatic specification for parameter of file type
@end itemize


@menu
* mime/editor-mode::
* single-part operations::
* enclosure operation::
* other operations of mime/editor-mode::
@end menu


@node mime/editor-mode, single-part operations, tm-edit, tm-edit
@comment  node-name,  next,  previous,  up
@section mime/editor-mode
@cindex mime/editor-mode

@emph{mime/editor-mode} is a minor mode to compose MIME message.
In this mode, @emph{tag} represents various kinds of data, you can
edit multi-part message.

There are 2 kinds of @emph{tag}s:

@itemize @bullet
@item single-part tag
@item multi-part tag
@end itemize

single-part tag represents single part, this form is following:

@example
        --[[TYPE/SUBTYPE;PARAMETERS][ENCODING]
        OPTIONAL-FIELDS]
@end example

TYPE/SUBTYPE and PARAMETERS indicates type/subtype and parameters of
Content-Type field. TYPE/SUBTYPE is required, PARAMETERS is optional.

ENCODING indicates Content-Transfer-Encoding field. It is optional too.

OPTIONAL-FIELDS is to represent another fields except Content-Type
field and Content-Transfer-Encoding field.

multi-part tags represent multi part. They consist of a pair of 
@emph{multi-part beginning tag} and @emph{multi-part ending tag}.

@emph{multi-part beginning tag}'s form is following:

@example
        --<<TYPE>>-@{
@end example

@emph{multi-part ending tag}'s form is following:

@example
        --@}-<<TYPE>>
@end example

A region from multi-part beginning tag to multi-part ending tag is
called as @emph{enclosure}.


@node single-part operations, enclosure operation, mime/editor-mode, tm-edit
@comment  node-name,  next,  previous,  up
@section single-part operations
@cindex single-part

Operations to make single-part are following:

@table @kbd
@item @key{C-c C-x C-t}
Insert single-part tag indicates text part.

@item @key{C-c C-x C-i}
Insert file as a MIME attachment.

@item @key{C-c C-x C-e}
Insert external part.

@item @key{C-c C-x C-v}
Record audio input until @key{C-g} is pressed, and insert as a audio
part. (It requires /dev/audio in default.)

@item @key{C-c C-x C-y}
Insert current (mail or news) message. (It is MUA depended.)

@item @key{C-c C-x C-m}
Insert mail message. (It is MUA depended.)

@item @key{C-c C-x C-w, C-c C-x C-s}
Insert signature.

@item @key{C-c C-x C-k}
Insert PGP public key. (It requires Mailcrypt package.)

@item @key{C-c C-x t}
Insert any  single-part tag.
@end table


@node enclosure operation, other operations of mime/editor-mode, single-part operations, tm-edit
@comment  node-name,  next,  previous,  up
@section enclosure operations
@cindex multi-part
@cindex enclosure

Operations to make enclosure are following:

@table @kbd
@item @key{C-c C-x a}
Enclose specified region as multipart/alternative.

@item @key{C-c C-x p}
Enclose specified region as multipart/parallel.

@item @key{C-c C-x m}
Enclose specified region as multipart/mixed.

@item @key{C-c C-x d}
Enclose specified region as multipart/digest.

@item @key{C-c C-x s}
Digital-sign to specified region. (*1)

@item @key{C-c C-x e}
Encrypt to specified region. (*1)
@end table

@b{[Notice]}
@enumerate
@item
It requires Mailcrypt package and pgp package. In addition, please set
symbol @code{pgp-elkins} or @code{pgp-kazu} to
variable @code{mime-editor/signing-type} and
@code{mime-editor/encrypting-type}.

@code{pgp-elkins} indicates draft-elkins-pem-pgp-02.txt,
@code{pgp-kazu} indicates draft-kazu-pgp-mime-00.txt.
@end enumerate


@node other operations of mime/editor-mode,  , enclosure operation, tm-edit
@comment  node-name,  next,  previous,  up
@section Another operation in mime/editor-mode.

There are another operations in mime/editor-mode.

@table @kbd
@item @key{C-c C-c}
Send current editing message.

@item @key{C-c C-x C-p}
Preview current editing message.

@item @key{C-c C-x C-z}
Exit mime/editor-mode. (@key{M-x mime/edit-again} is available to
reedit.)

@item @key{C-c C-x ?}
Display help message.

@item @key{M-x mime-editor/set-split}
Set current editing message to enable automatic splitting or not.
Form of automatic split messages is message/partial.

@item @key{M-x mime-editor/set-sign}
Set current editing message to digital-sign or not. (*1)

@item @key{M-x mime-editor/set-encrypt}
Set current editing message to encrypt or not. (*1)
@end table

@b{[Notice]}
@enumerate
@item
It requires Mailcrypt package and pgp package. In addition, please set
symbol @code{pgp-elkins} or @code{pgp-kazu} to
variable @code{mime-editor/signing-type} and
@code{mime-editor/encrypting-type}.

@code{pgp-elkins} indicates draft-elkins-pem-pgp-02.txt,
@code{pgp-kazu} indicates draft-kazu-pgp-mime-00.txt.
@end enumerate
