#!/bin/sh -
#
# $Id: tm-au,v 1.2 1996/12/29 00:14:55 steve Exp $
#

if [ "$TM_TMP_DIR" = "" ]; then
	TM_TMP_DIR=/tmp
	export TM_TMP_DIR
fi

if [ "$5" = "" ]; then
	filename="$TM_TMP_DIR/mime$$.au"
else
	filename="$TM_TMP_DIR/$5"
fi


case "$4" in
"play")
	echo "$2; $3 ->"
	tmdecode $3 $1 $filename
	if [ "$AUDIOSERVER" = "" ]; then
		if [ `uname` = "IRIX" ]; then
			sfplay $filename
		else
			cat $filename > /dev/audio
		fi
	else
		autool -v 40 $filename
	fi
	trap 'rm -f $filename' 0 1 2 3 13 15
	;;
"extract")
	echo "$2; $3 -> $filename"
	echo "extract to $filename"
	tmdecode $3 $1 $filename
	;;
esac
