#!/bin/sh -
#
# $Id: tm-au,v 1.4 1997/01/23 05:29:22 steve Exp $
#

PATH=${PATH:-/usr/bin:/bin}:`dirname $0 2>/dev/null`; export PATH

if [ "$TM_TMP_DIR" = "" ]; then
	TM_TMP_DIR=/tmp
	export TM_TMP_DIR
fi

if [ "$5" = "" ]; then
	filename="$TM_TMP_DIR/mime$$.au"
else
	filename="$TM_TMP_DIR/$5"
fi


case "$4" in
"play")
	echo "$2; $3 ->"
	tmdecode $3 $1 $filename
	if [ "$AUDIOSERVER" = "" ]; then
          case "`uname`" in
            IRIX )  sfplay $filename           ;;
            OSF1 )  decsound -play $filename   ;;
            *    )  cat $filename > /dev/audio ;;
          esac
	else
          autool -v 40 $filename
	fi
        
	trap 'rm -f $filename' 0 1 2 3 13 15
	;;
"extract")
	echo "$2; $3 -> $filename"
	echo "extract to $filename"
	tmdecode $3 $1 $filename
	;;
esac
