#!/bin/sh -
#
# $Id: tm-au,v 1.1.1.1 1996/12/18 22:42:33 steve Exp $
#

if [ "$TM_TMP_DIR" = "" ]; then
	TM_TMP_DIR=/tmp
	export TM_TMP_DIR
fi

if [ "$5" = "" ]; then
	filename="$TM_TMP_DIR/mime$$.au"
else
	filename="$TM_TMP_DIR/$5"
fi


case "$4" in
"play")
	echo "$2; $3 ->"
	if [ "$AUDIOSERVER" = "" ]; then
		if [ `uname` = "IRIX" ]; then
			tmdecode $3 $1 $filename
			sfplay $filename
			trap 'rm -f $filename' 0 1 2 3 13 15
		else
			tmdecode $3 $1 /dev/audio
		fi
	else
		tmdecode $3 $1 $filename
		autool -v 40 $filename
		trap 'rm -f $filename' 0 1 2 3 13 15
	fi
	;;
"extract")
	echo "$2; $3 -> $filename"
	echo "extract to $filename"
	tmdecode $3 $1 $filename
	;;
esac
