#!/bin/sh -
#
# $Id: tm-file,v 1.3 1997/01/11 20:13:51 steve Exp $
#

PATH=${PATH:-/usr/bin:/bin}:`dirname $0 2>/dev/null`; export PATH

if [ "$TM_TMP_DIR" = "" ]; then
	TM_TMP_DIR=/tmp
	export TM_TMP_DIR
fi

if [ "$5" = "" ]; then
	filename="$TM_TMP_DIR/mime$$"
else
	filename="$TM_TMP_DIR/$5"
fi


echo "$2; $3 -> $filename"

tmdecode $3 $1 $filename
