#!/bin/sh -
#
# $Id: tm-plain,v 1.3 1997/01/11 20:13:52 steve Exp $
#

PATH=${PATH:-/usr/bin:/bin}:`dirname $0 2>/dev/null`; export PATH

if [ "$TM_TMP_DIR" = "" ]; then
	TM_TMP_DIR=/tmp
	export TM_TMP_DIR
fi
if [ "$5" = "" ]; then
	filename="$TM_TMP_DIR/mime$$.pln"
else
	filename="$TM_TMP_DIR/$5"
fi

case "$4" in
"play")
	echo "$2; $3 ->"
	tmdecode "$3" "$1" /dev/stdout
	;;
"extract")
	echo "$2; $3 -> $filename"
	echo "extract to $filename"
	tmdecode "$3" "$1" $filename
	;;
"print")
	echo "$2; $3 ->"
	tmdecode "$3" "$1" /dev/stdout | lpr
	;;
esac
