(custom-put 'telnet 'custom-loads '("telnet"))
(custom-put 'ssh 'custom-loads '("ssh"))
(custom-put 'shell-faces 'custom-loads '("shell"))
(custom-put 'shell-directories 'custom-loads '("shell"))
(custom-put 'shell 'custom-loads '("shell"))
(custom-put 'rlogin 'custom-loads '("rlogin"))
(custom-put 'comint-source 'custom-loads '("comint"))
(custom-put 'comint-completion 'custom-loads '("comint"))
(custom-put 'comint 'custom-loads '("comint-xemacs" "comint" "telnet"))
(custom-put 'background 'custom-loads '("background"))
