#!/bin/sh
EMACS=${1:-emacs}
if [ -z "$HOME" ]; then
    HOME=`(cd ; pwd)`
fi

WITH=`   ${EMACS} -batch -l ${HOME}/.emacs             -eval '(princ (file-truename (locate-library "custom")))'`
WITHOUT=`${EMACS} -batch -q -no-site-file -l docomp.el -eval '(princ (file-truename (locate-library "custom")))'`

if [ "${WITH}" = "${WITHOUT}" ]; then
    exit 0
else
    echo "WARNING -- WARNING -- WARNING"
    echo "Found custom in different places with and without ${HOME}/.emacs"
    echo
    echo "This could cause potential problems.  Please recompile with"
    echo "the environment variable WIDGETDIR set correctly.  Try this"
    echo "command:"
    echo "make WIDGETDIR=${WITH}"
    exit 1
fi
