(custom-put 'ssl 'custom-loads '("ssl"))
(custom-put 'url-gateway 'custom-loads '("url-gw"))
(custom-put 'url 'custom-loads '("url-gw" "url-irc" "url-vars" "url"))
(custom-put 'url-file 'custom-loads '("url-cache" "url-vars"))
(custom-put 'url-cache 'custom-loads '("url-cache" "url-vars"))
(custom-put 'url-history 'custom-loads '("url-vars"))
(custom-put 'url-cookie 'custom-loads '("url-cookie" "url-vars"))
(custom-put 'url-mime 'custom-loads '("url-vars"))
(custom-put 'url-hairy 'custom-loads '("url-vars"))
(custom-put 'w3 'custom-loads '("w3-cus" "w3-script"))
(custom-put 'w3-files 'custom-loads '("w3-cus"))
(custom-put 'w3-images 'custom-loads '("w3-cus"))
(custom-put 'w3-printing 'custom-loads '("w3-cus"))
(custom-put 'w3-menus 'custom-loads '("w3-cus" "w3-menu"))
(custom-put 'w3-parsing 'custom-loads '("w3-cus"))
(custom-put 'w3-display 'custom-loads '("w3-cus"))
(custom-put 'w3-hooks 'custom-loads '("w3-cus"))
(custom-put 'w3-scripting 'custom-loads '("w3-script"))
