(custom-put 'html 'custom-loads '("psgml-html"))
(custom-put 'psgml-html 'custom-loads '("psgml-html"))
(custom-put 'sgml 'custom-loads '("psgml-html" "psgml"))
(custom-put 'psgml 'custom-loads '("psgml-html" "psgml"))
(custom-put 'psgml-insert 'custom-loads '("psgml"))
(custom-put 'psgml-dtd 'custom-loads '("psgml"))
(custom-put 'tempo 'custom-loads '("tempo"))
