(put 'gnus-start 'custom-loads '("gnus-group" "gnus-int" "gnus-start" "gnus-util" "gnus"))
(put 'extensions 'custom-loads '("wid-edit"))
(put 'message 'custom-loads '("message" "sendmail"))
(put 'gnus-score-expire 'custom-loads '("gnus-kill" "gnus-score"))
(put 'gnus-score-kill 'custom-loads '("gnus-kill"))
(put 'gnus-message 'custom-loads '("message"))
(put 'gnus-summary-sort 'custom-loads '("gnus-sum"))
(put 'nnmail-procmail 'custom-loads '("nnmail"))
(put 'ssl 'custom-loads '("ssl"))
(put 'telnet 'custom-loads '("telnet"))
(put 'widgets 'custom-loads '("wid-browse" "wid-edit"))
(put 'environment 'custom-loads '("cus-edit" "dired-faces"))
(put 'gnus-article-buttons 'custom-loads '("gnus-art"))
(put 'gnus-extract-archive 'custom-loads '("gnus-uu"))
(put 'gnus-article-headers 'custom-loads '("gnus-art" "gnus-sum"))
(put 'gnus-score 'custom-loads '("gnus-nocem" "gnus"))
(put 'gnus-summary-various 'custom-loads '("gnus-sum"))
(put 'gnus-topic 'custom-loads '("gnus-topic"))
(put 'gnus-article-emphasis 'custom-loads '("gnus-art"))
(put 'earcon 'custom-loads '("earcon"))
(put 'gnus-group-foreign 'custom-loads '("gnus-group"))
(put 'gnus-article-washing 'custom-loads '("gnus-art"))
(put 'mail 'custom-loads '("gnus" "message"))
(put 'gnus-summary-exit 'custom-loads '("gnus-sum"))
(put 'gnus-article-saving 'custom-loads '("gnus-art"))
(put 'gnus-extract-view 'custom-loads '("gnus-sum" "gnus-uu"))
(put 'comint 'custom-loads '("comint-xemacs" "telnet"))
(put 'gnus-group-listing 'custom-loads '("gnus-group"))
(put 'gnus-summary 'custom-loads '("gnus-sum" "gnus"))
(put 'message-headers 'custom-loads '("message"))
(put 'gnus-group-select 'custom-loads '("gnus-sum"))
(put 'display-time 'custom-loads '("time"))
(put 'hypermedia 'custom-loads '("wid-edit" "w3-cus"))
(put 'w3-advanced 'custom-loads '("w3-cus"))
(put 'w3-menus 'custom-loads '("w3-cus" "w3-menu"))
(put 'gnus-summary-mail 'custom-loads '("gnus-sum"))
(put 'gnus-score-default 'custom-loads '("gnus-score" "gnus-sum"))
(put 'nnmail-expire 'custom-loads '("nnmail"))
(put 'gnus-thread 'custom-loads '("gnus-sum"))
(put 'gnus-nocem 'custom-loads '("gnus-nocem"))
(put 'gnus-threading 'custom-loads '("gnus-sum"))
(put 'applications 'custom-loads '("cus-edit" "time"))
(put 'gnus-summary-maneuvering 'custom-loads '("gnus-sum"))
(put 'gnus-extract 'custom-loads '("gnus" "gnus-uu"))
(put 'help 'custom-loads '("cus-edit"))
(put 'nnmail-split 'custom-loads '("nnmail"))
(put 'gnus-article-various 'custom-loads '("gnus-art" "gnus-sum"))
(put 'message-sending 'custom-loads '("message"))
(put 'w3-files 'custom-loads '("w3-cus"))
(put 'widget-browse 'custom-loads '("wid-browse"))
(put 'gnus-article 'custom-loads '("gnus-art" "gnus-cite"))
(put 'gnus 'custom-loads '("gnus-art" "gnus-async" "gnus-cache" "gnus-demon" "gnus-dup" "gnus-eform" "gnus-uu" "gnus-win" "gnus" "nnmail"))
(put 'gnus-treading 'custom-loads '("gnus-sum"))
(put 'nnmail 'custom-loads '("nnmail"))
(put 'gnus-article-hiding 'custom-loads '("gnus-art" "gnus-sum"))
(put 'customize 'custom-loads '("wid-edit" "custom" "cus-face" "cus-edit"))
(put 'w3-printing 'custom-loads '("w3-cus"))
(put 'nnmail-duplicate 'custom-loads '("nnmail"))
(put 'gnus-summary-visual 'custom-loads '("gnus-sum" "gnus"))
(put 'w3-images 'custom-loads '("w3-cus"))
(put 'gnus-group-various 'custom-loads '("gnus-group"))
(put 'nnmail-retrieve 'custom-loads '("nnmail"))
(put 'message-interface 'custom-loads '("message"))
(put 'gnus-group 'custom-loads '("gnus-topic" "gnus"))
(put 'programming 'custom-loads '("cus-edit"))
(put 'gnus-article-signature 'custom-loads '("gnus-art"))
(put 'dired 'custom-loads '("dired-faces"))
(put 'gnus-duplicate 'custom-loads '("gnus-dup"))
(put 'gnus-score-adapt 'custom-loads '("gnus-score"))
(put 'nnmail-various 'custom-loads '("nnmail"))
(put 'nnmail-files 'custom-loads '("nnmail"))
(put 'gnus-asynchronous 'custom-loads '("gnus-async"))
(put 'gnus-visual 'custom-loads '("earcon" "gnus-art" "gnus-picon" "gnus" "smiley"))
(put 'message-forwarding 'custom-loads '("message"))
(put 'message-news 'custom-loads '("message"))
(put 'gnus-edit-form 'custom-loads '("gnus-eform"))
(put 'external 'custom-loads '("cus-edit"))
(put 'gnus-files 'custom-loads '("gnus" "nnmail"))
(put 'gnus-cite 'custom-loads '("gnus-cite"))
(put 'gnus-demon 'custom-loads '("gnus-demon"))
(put 'gnus-summary-choose 'custom-loads '("gnus-sum"))
(put 'development 'custom-loads '("cus-edit"))
(put 'gnus-windows 'custom-loads '("gnus-win"))
(put 'message-mail 'custom-loads '("message"))
(put 'message-various 'custom-loads '("message"))
(put 'gnus-group-levels 'custom-loads '("gnus-group"))
(put 'languages 'custom-loads '("cus-edit"))
(put 'gnus-summary-format 'custom-loads '("gnus-sum"))
(put 'gnus-score-decay 'custom-loads '("gnus-score"))
(put 'gnus-extract-post 'custom-loads '("gnus-uu"))
(put 'faces 'custom-loads '("cus-edit" "wid-edit" "gnus" "message"))
(put 'gnus-various 'custom-loads '("gnus-sum"))
(put 'gnus-article-highlight 'custom-loads '("gnus-art"))
(put 'emacs 'custom-loads '("cus-edit" "ssl"))
(put 'processes 'custom-loads '("comint-xemacs"))
(put 'news 'custom-loads '("gnus" "message"))
(put 'w3-hooks 'custom-loads '("w3-cus"))
(put 'message-insertion 'custom-loads '("message"))
(put 'wp 'custom-loads '("cus-edit"))
(put 'message-faces 'custom-loads '("message"))
(put 'w3 'custom-loads '("w3-cus" "w3-script"))
(put 'gnus-score-files 'custom-loads '("gnus-score"))
(put 'gnus-summary-marks 'custom-loads '("gnus-sum"))
(put 'picons 'custom-loads '("gnus-picon"))
(put 'nnmail-prepare 'custom-loads '("nnmail"))
(put 'w3-display 'custom-loads '("w3-cus"))
(put 'w3-parsing 'custom-loads '("w3-cus"))
(put 'message-buffers 'custom-loads '("message"))
(put 'editing 'custom-loads '("cus-edit"))
(put 'gnus-article-mime 'custom-loads '("gnus-art" "gnus-sum"))
(put 'w3-scripting 'custom-loads '("w3-script"))
