(custom-put 'mouse 'custom-loads '("mouse"))
(custom-put 'minibuffer 'custom-loads '("minibuf"))
(custom-put 'environment 'custom-loads '("frame" "minibuf" "modeline" "sound"))
(custom-put 'sound 'custom-loads '("sound"))
(custom-put 'auto-save 'custom-loads '("files"))
(custom-put 'editing-basics 'custom-loads '("cmdloop" "simple" "files" "lisp"))
(custom-put 'help-appearance 'custom-loads '("help"))
(custom-put 'lisp 'custom-loads '("lisp"))
(custom-put 'help 'custom-loads '("help"))
(custom-put 'keyboard 'custom-loads '("cmdloop"))
(custom-put 'backup 'custom-loads '("files"))
(custom-put 'frames 'custom-loads '("frame" "window-xemacs" "gui"))
(custom-put 'abbrev 'custom-loads '("files"))
(custom-put 'dired 'custom-loads '("files"))
(custom-put 'killing 'custom-loads '("simple"))
(custom-put 'paren-blinking 'custom-loads '("simple"))
(custom-put 'find-file 'custom-loads '("files"))
(custom-put 'files 'custom-loads '("files"))
(custom-put 'fill-comments 'custom-loads '("simple"))
(custom-put 'windows 'custom-loads '("window" "window-xemacs"))
(custom-put 'fill 'custom-loads '("simple"))
(custom-put 'vc 'custom-loads '("files"))
(custom-put 'isearch 'custom-loads '("isearch-mode"))
(custom-put 'modeline 'custom-loads '("modeline"))
(custom-put 'editing 'custom-loads '("simple"))
(custom-put 'matching 'custom-loads '("simple" "isearch-mode"))
