(put 'gnus-start 'custom-loads '("gnus-group" "gnus-int" "gnus-start" "gnus-util" "gnus"))
(put 'extensions 'custom-loads '("wid-edit" "page-ext" "time-stamp" "tempo" "eldoc"))
(put 'change-log 'custom-loads '("add-log"))
(put 'message 'custom-loads '("message" "highlight-headers" "sendmail"))
(put 'filladapt 'custom-loads '("filladapt"))
(put 'psgml-dtd 'custom-loads '("psgml"))
(put 'copyright 'custom-loads '("upd-copyr"))
(put 'gnus-score-expire 'custom-loads '("gnus-kill" "gnus-score"))
(put 'gnus-score-kill 'custom-loads '("gnus-kill"))
(put 'eldoc 'custom-loads '("eldoc"))
(put 'prolog 'custom-loads '("prolog"))
(put 'bookmark 'custom-loads '("bookmark"))
(put 'recent-files-menu 'custom-loads '("recent-files"))
(put 'url 'custom-loads '("url-gw" "url-irc" "url-vars" "url"))
(put 'custom-faces 'custom-loads '("cus-edit"))
(put 'abbrev-mode 'custom-loads '())
(put 'execute 'custom-loads '())
(put 'gnus-message 'custom-loads '("message"))
(put 'mouse 'custom-loads '("mouse" "outl-mouse" "avoid"))
(put 'mail-abbrevs 'custom-loads '("mail-abbrevs"))
(put 'gnus-summary-sort 'custom-loads '("gnus-sum"))
(put 'nnmail-procmail 'custom-loads '("nnmail"))
(put 'pascal 'custom-loads '("pascal"))
(put 'tex 'custom-loads '("texnfo-tex"))
(put 'ssl 'custom-loads '("ssl"))
(put 'tcl 'custom-loads '("tcl"))
(put 'limits 'custom-loads '())
(put 'igrep 'custom-loads '("igrep"))
(put 'telnet 'custom-loads '("telnet"))
(put 'widgets 'custom-loads '("wid-browse" "wid-edit"))
(put 'minibuffer 'custom-loads '("minibuf" "detached-minibuf"))
(put 'environment 'custom-loads '("minibuf" "modeline" "x-toolbar" "cus-edit" "dired-faces" "sound"))
(put 'shell 'custom-loads '("shell"))
(put 'sound 'custom-loads '("sound"))
(put 'gnus-article-buttons 'custom-loads '("gnus-art"))
(put 'gnus-extract-archive 'custom-loads '("gnus-uu"))
(put 'html 'custom-loads '("psgml-html"))
(put 'cc-style 'custom-loads '("cc-mode"))
(put 'gnus-article-headers 'custom-loads '("gnus-art" "gnus-sum"))
(put 'holidays 'custom-loads '("calendar"))
(put 'texinfo 'custom-loads '("texinfo" "texnfo-tex"))
(put 'gnus-score 'custom-loads '("gnus-nocem" "gnus"))
(put 'gnus-summary-various 'custom-loads '("gnus-sum"))
(put 'terminals 'custom-loads '("gnuserv"))
(put 'gnus-topic 'custom-loads '("gnus-topic"))
(put 'comint-completion 'custom-loads '("comint"))
(put 'gnus-article-emphasis 'custom-loads '("gnus-art"))
(put 'earcon 'custom-loads '("earcon"))
(put 'boolean 'custom-loads '("bookmark"))
(put 'auto-save 'custom-loads '("auto-save"))
(put 'gnus-group-foreign 'custom-loads '("gnus-group"))
(put 'xrdb 'custom-loads '("xrdb-mode"))
(put 'gnus-article-washing 'custom-loads '("gnus-xmas" "gnus-art"))
(put 'ispell 'custom-loads '("ispell"))
(put 'mail 'custom-loads '("gnus" "message" "mh-e" "mail-abbrevs" "feedmail" "supercite" "highlight-headers" "smtpmail"))
(put 'gnus-summary-exit 'custom-loads '("gnus-sum"))
(put 'fortran-indent 'custom-loads '("fortran"))
(put 'ps-print-face 'custom-loads '("ps-print"))
(put 'gnus-article-saving 'custom-loads '("gnus-art"))
(put 'gnus-extract-view 'custom-loads '("gnus-sum" "gnus-uu"))
(put 'crypt 'custom-loads '("crypt"))
(put 'object 'custom-loads '("gopher"))
(put 'comint 'custom-loads '("comint-xemacs" "comint" "telnet"))
(put 'gnus-group-listing 'custom-loads '("gnus-group"))
(put 'man 'custom-loads '("man"))
(put 'lpr 'custom-loads '("lpr"))
(put 'gnus-summary 'custom-loads '("gnus-sum" "gnus"))
(put 'message-headers 'custom-loads '("message"))
(put 'ps-print-header 'custom-loads '("ps-print"))
(put 'docs 'custom-loads '("texinfo" "hyper-apropos" "makeinfo"))
(put 'lisp-indent 'custom-loads '("cl-indent"))
(put 'completion 'custom-loads '("completion"))
(put 'tools 'custom-loads '("ediff" "make-mode" "add-log" "diff" "func-menu" "generic-sc" "rcompile"))
(put 'cc-comment 'custom-loads '("cc-mode"))
(put 'url-cookie 'custom-loads '("url-cookie" "url-vars"))
(put 'uniquify 'custom-loads '("uniquify"))
(put 'recent-files 'custom-loads '("recent-files"))
(put 'editing-basics 'custom-loads '("simple"))
(put 'gnus-group-select 'custom-loads '("gnus-sum"))
(put 'display-time-balloon 'custom-loads '("time"))
(put 'internal 'custom-loads '("cus-edit"))
(put 'calendar 'custom-loads '("calendar"))
(put 'dabbrev 'custom-loads '("dabbrev"))
(put 'help-appearance 'custom-loads '("help"))
(put 'display-time 'custom-loads '("time"))
(put 'hypermedia 'custom-loads '("wid-edit" "gopher" "browse-url" "url-vars" "w3-cus"))
(put 'save-place 'custom-loads '("saveplace"))
(put 'w3-advanced 'custom-loads '("w3-cus"))
(put 'lisp 'custom-loads '("edebug" "cl-indent" "elp"))
(put 'jka-compr 'custom-loads '("jka-compr"))
(put 'rlogin 'custom-loads '("rlogin"))
(put 'proces-basics 'custom-loads '())
(put 'diff 'custom-loads '("diff"))
(put 'shell-faces 'custom-loads '("shell"))
(put 'sh-script 'custom-loads '("sh-script"))
(put 'w3-menus 'custom-loads '("w3-cus" "w3-menu"))
(put 'gnus-summary-mail 'custom-loads '("gnus-sum"))
(put 'elp 'custom-loads '("elp"))
(put 'psgml 'custom-loads '("psgml-html" "psgml"))
(put 'supercite-cite 'custom-loads '("supercite"))
(put 'gnus-score-default 'custom-loads '("gnus-score" "gnus-sum"))
(put 'nnmail-expire 'custom-loads '("nnmail"))
(put 'gnus-thread 'custom-loads '("gnus-sum"))
(put 'gnus-nocem 'custom-loads '("gnus-nocem"))
(put 'gnus-threading 'custom-loads '("gnus-sum"))
(put 'ediff-diff 'custom-loads '("ediff-diff"))
(put 'applications 'custom-loads '("cus-edit" "uniquify"))
(put 'outlines 'custom-loads '("outl-mouse" "whitespace-mode"))
(put 'paren-matching 'custom-loads '("simple" "paren"))
(put 'time-stamp 'custom-loads '("time-stamp"))
(put 'gnus-summary-maneuvering 'custom-loads '("gnus-sum"))
(put 'avoid 'custom-loads '("avoid"))
(put 'f90 'custom-loads '("f90"))
(put 'gnus-extract 'custom-loads '("gnus" "gnus-uu"))
(put 'help 'custom-loads '("help" "cus-edit" "info" "man"))
(put 'supercite 'custom-loads '("supercite"))
(put 'generic-sc 'custom-loads '("generic-sc"))
(put 'local 'custom-loads '("calendar" "gopher"))
(put 'nnmail-split 'custom-loads '("nnmail"))
(put 'keyboard 'custom-loads '())
(put 'minubuffer 'custom-loads '("minibuf"))
(put 'asm 'custom-loads '("asm-mode"))
(put 'installation 'custom-loads '())
(put 'url-gateway 'custom-loads '("url-gw"))
(put 'gnus-article-various 'custom-loads '("gnus-art" "gnus-sum"))
(put 'mh-hook 'custom-loads '("mh-e"))
(put 'message-sending 'custom-loads '("message"))
(put 'w3-files 'custom-loads '("w3-cus"))
(put 'widget-browse 'custom-loads '("wid-browse"))
(put 'data 'custom-loads '("auto-save" "crypt" "jka-compr" "recent-files" "saveplace" "time-stamp"))
(put 'gnus-article 'custom-loads '("gnus-art" "gnus-cite"))
(put 'edebug 'custom-loads '("edebug"))
(put 'ps-print 'custom-loads '("ps-print"))
(put 'cc-indent 'custom-loads '("cc-mode"))
(put 'compression 'custom-loads '("jka-compr"))
(put 'comm 'custom-loads '("ssl"))
(put 'gnus 'custom-loads '("gnus-art" "gnus-async" "gnus-cache" "gnus-demon" "gnus-dup" "gnus-eform" "gnus-uu" "gnus-win" "gnus-xmas" "gnus" "nnmail"))
(put 'ps-print-font 'custom-loads '("ps-print"))
(put 'id-select 'custom-loads '("id-select"))
(put 'gnus-xmas 'custom-loads '("gnus-xmas"))
(put 'fortran-comment 'custom-loads '("fortran"))
(put 'outl-mouse 'custom-loads '("outl-mouse"))
(put 'gnus-treading 'custom-loads '("gnus-sum"))
(put 'url-cache 'custom-loads '("url-cache" "url-vars"))
(put 'frames 'custom-loads '("rsz-minibuf" "ediff-wind" "balloon-help" "desktop" "detached-minibuf"))
(put 'psgml-html 'custom-loads '("psgml-html"))
(put 'nnmail 'custom-loads '("nnmail"))
(put 'gnus-article-hiding 'custom-loads '("gnus-art" "gnus-sum"))
(put 'customize 'custom-loads '("wid-edit" "cus-face" "cus-edit"))
(put 'w3-printing 'custom-loads '("w3-cus"))
(put 'nnmail-duplicate 'custom-loads '("nnmail"))
(put 'supercite-attr 'custom-loads '("supercite"))
(put 'gnus-summary-visual 'custom-loads '("gnus-sum" "gnus"))
(put 'w3-images 'custom-loads '("w3-cus"))
(put 'shell-directories 'custom-loads '("shell"))
(put 'desktop 'custom-loads '("desktop"))
(put 'gnus-group-various 'custom-loads '("gnus-group"))
(put 'abbrev 'custom-loads '("cus-edit" "dabbrev"))
(put 'f90-indent 'custom-loads '("f90"))
(put 'nnmail-retrieve 'custom-loads '("nnmail"))
(put 'url-history 'custom-loads '("url-vars"))
(put 'message-interface 'custom-loads '("message"))
(put 'gnus-group 'custom-loads '("gnus-topic" "gnus"))
(put 'remote-compile 'custom-loads '("rcompile"))
(put 'programming 'custom-loads '("cus-edit" "compile"))
(put 'gnus-article-signature 'custom-loads '("gnus-art"))
(put 'toolbar 'custom-loads '("x-toolbar"))
(put 'compilation 'custom-loads '("compile"))
(put 'dired 'custom-loads '("dired-faces"))
(put 'gnus-duplicate 'custom-loads '("gnus-dup"))
(put 'url-hairy 'custom-loads '("url-vars"))
(put 'sgml 'custom-loads '("psgml-html" "psgml"))
(put 'gnus-score-adapt 'custom-loads '("gnus-score"))
(put 'comint-source 'custom-loads '("comint"))
(put 'makeinfo 'custom-loads '("makeinfo"))
(put 'nnmail-various 'custom-loads '("nnmail"))
(put 'fume 'custom-loads '("func-menu"))
(put 'cc-auto 'custom-loads '("cc-mode"))
(put 'nnmail-files 'custom-loads '("nnmail"))
(put 'gnus-asynchronous 'custom-loads '("gnus-async"))
(put 'url-mime 'custom-loads '("url-vars"))
(put 'gnus-visual 'custom-loads '("earcon" "gnus-art" "gnus-picon" "gnus" "smiley"))
(put 'c-macro 'custom-loads '("cmacexp"))
(put 'message-forwarding 'custom-loads '("message"))
(put 'killing 'custom-loads '("simple"))
(put 'smtpmail 'custom-loads '("smtpmail"))
(put 'message-news 'custom-loads '("message"))
(put 'paren-blinking 'custom-loads '("simple"))
(put 'vrml-mode 'custom-loads '("vrml-mode"))
(put 'vrml 'custom-loads '("vrml-mode"))
(put 'games 'custom-loads '("xmine"))
(put 'gnus-edit-form 'custom-loads '("gnus-eform"))
(put 'fast-lock 'custom-loads '("fast-lock"))
(put 'external 'custom-loads '("cus-edit"))
(put 'gnus-files 'custom-loads '("gnus" "nnmail"))
(put 'fortran 'custom-loads '("f90" "fortran"))
(put 'ediff-merge 'custom-loads '("ediff-merg"))
(put 'gnus-cite 'custom-loads '("gnus-cite"))
(put 'gnus-demon 'custom-loads '("gnus-demon"))
(put 'gnus-summary-choose 'custom-loads '("gnus-sum"))
(put 'cc-mode 'custom-loads '("cc-mode"))
(put 'development 'custom-loads '("cus-edit"))
(put 'mh-buffer 'custom-loads '("mh-utils"))
(put 'tempo 'custom-loads '("tempo"))
(put 'gnuserv 'custom-loads '("gnuserv"))
(put 'ps-print-horizontal 'custom-loads '("ps-print"))
(put 'gnus-windows 'custom-loads '("gnus-win"))
(put 'maint 'custom-loads '("upd-copyr"))
(put 'detached-minibuf 'custom-loads '("detached-minibuf"))
(put 'message-mail 'custom-loads '("message"))
(put 'ediff-mult 'custom-loads '("ediff-mult"))
(put 'windows 'custom-loads '())
(put 'message-various 'custom-loads '("message"))
(put 'resize-minibuffer 'custom-loads '("rsz-minibuf"))
(put 'gnus-group-levels 'custom-loads '("gnus-group"))
(put 'languages 'custom-loads '("cus-edit" "asm-mode" "fortran" "pascal" "prolog" "rexx-mode" "sh-script" "tcl" "verilog-mode" "vrml-mode" "xrdb-mode" "psgml"))
(put 'gnus-summary-format 'custom-loads '("gnus-sum"))
(put 'gnus-score-decay 'custom-loads '("gnus-score"))
(put 'fill 'custom-loads '())
(put 'balloon-help 'custom-loads '("balloon-help"))
(put 'gnus-extract-post 'custom-loads '("gnus-uu"))
(put 'debug 'custom-loads '())
(put 'supercite-hooks 'custom-loads '("supercite"))
(put 'display 'custom-loads '())
(put 'texinfo-tex 'custom-loads '("texnfo-tex"))
(put 'faces 'custom-loads '("cus-edit" "wid-edit" "gnus" "message" "fast-lock" "ps-print" "highlight-headers" "font"))
(put 'passwd 'custom-loads '("passwd"))
(put 'pages 'custom-loads '("page-ext"))
(put 'diary 'custom-loads '("calendar"))
(put 'gnus-various 'custom-loads '("gnus-sum"))
(put 'cc-syntax 'custom-loads '("cc-mode"))
(put 'mh-compose 'custom-loads '("mh-comp"))
(put 'xmine 'custom-loads '("xmine"))
(put 'supercite-frames 'custom-loads '("supercite"))
(put 'browse-url 'custom-loads '("browse-url"))
(put 'feedmail 'custom-loads '("feedmail"))
(put 'enriched 'custom-loads '("enriched"))
(put 'gnus-article-highlight 'custom-loads '("gnus-art"))
(put 'emacs 'custom-loads '("cus-edit"))
(put 'processes 'custom-loads '("background" "comint" "rlogin" "shell" "cus-edit" "executable" "gnuserv" "igrep" "ispell" "rcompile" "passwd"))
(put 'news 'custom-loads '("gnus" "message" "supercite" "highlight-headers"))
(put 'rexx 'custom-loads '("rexx-mode"))
(put 'w3-hooks 'custom-loads '("w3-cus"))
(put 'executable 'custom-loads '("executable"))
(put 'highlight-headers 'custom-loads '("highlight-headers"))
(put 'message-insertion 'custom-loads '("message"))
(put 'hyper-apropos 'custom-loads '("hyper-apropos"))
(put 'psgml-insert 'custom-loads '("psgml"))
(put 'wp 'custom-loads '("cus-edit" "enriched" "lpr" "ps-print"))
(put 'background 'custom-loads '("background"))
(put 'message-faces 'custom-loads '("message"))
(put 'w3 'custom-loads '("w3-cus" "w3-script"))
(put 'sh 'custom-loads '("sh-script"))
(put 'ps-print-vertical 'custom-loads '("ps-print"))
(put 'url-file 'custom-loads '("url-cache" "url-vars"))
(put 'alloc 'custom-loads '())
(put 'isearch 'custom-loads '("isearch-mode"))
(put 'mh 'custom-loads '("mh-comp" "mh-e" "mh-utils"))
(put 'gnus-score-files 'custom-loads '("gnus-score"))
(put 'gopher 'custom-loads '("gopher"))
(put 'modeline 'custom-loads '("modeline"))
(put 'makefile-mode 'custom-loads '("make-mode"))
(put 'gnus-summary-marks 'custom-loads '("gnus-sum"))
(put 'appt 'custom-loads '("appt"))
(put 'picons 'custom-loads '("gnus-picon"))
(put 'nnmail-prepare 'custom-loads '("nnmail"))
(put 'whitespace 'custom-loads '("whitespace-mode"))
(put 'w3-display 'custom-loads '("w3-cus"))
(put 'w3-parsing 'custom-loads '("w3-cus"))
(put 'message-buffers 'custom-loads '("message"))
(put 'editing 'custom-loads '("simple" "cus-edit" "filladapt"))
(put 'matching 'custom-loads '("simple" "isearch-mode" "whitespace-mode" "bookmark" "completion"))
(put 'ediff 'custom-loads '("ediff-diff" "ediff-merg" "ediff-mult" "ediff-ptch" "ediff-wind" "ediff"))
(put 'gnus-article-mime 'custom-loads '("gnus-art" "gnus-sum"))
(put 'i18n 'custom-loads '("url-vars"))
(put 'ps-print-color 'custom-loads '("ps-print"))
(put 'info 'custom-loads '("info"))
(put 'w3-scripting 'custom-loads '("w3-script"))
(put 'unix 'custom-loads '("rlogin" "shell" "sh-script"))
(put 't 'custom-loads '("ps-print"))
(put 'c 'custom-loads '("cc-mode" "cmacexp"))
(put 'verilog-mode 'custom-loads '("verilog-mode"))
