(custom-put 'mail 'custom-loads '("mh-e"))
(custom-put 'mh-hook 'custom-loads '("mh-e"))
(custom-put 'mh-buffer 'custom-loads '("mh-utils"))
(custom-put 'mh-compose 'custom-loads '("mh-comp"))
(custom-put 'mh 'custom-loads '("mh-comp" "mh-e" "mh-utils"))
