;; a short example how to use the new Drag'n'Drop API in
;; combination with extents.
;;

(defun dnd-drop-somewhere (object)
  (message "Dropped somewhere else with :%s" object)
  t)

(defun do-nothing (object)
  nil)

(defun dnd-target1 (object)
  (message "Drop on target1 with: %s" object)
  t)

(defun dnd-target2 (object)
  (message "Drop on target2 with: %s" object)
  t)

(defun dnd-target3 (object)
  (message "Drop on target3 with: %s" object)
  t)

(defun make-drop-targets ()
  (let ((buf (get-buffer-create "*DND misc-user extent test buffer*"))
	(s nil)
	(e nil))
    (set-buffer buf)
    (pop-to-buffer buf)
    (setq s (point))
    (insert "[ DROP TARGET 1]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'dragdrop-drop-functions '(do-nothing dnd-target1))
    (set-extent-property ext 'mouse-face 'highlight)
    (insert "    ")
    (setq s (point))
    (insert "[ DROP TARGET 2]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'dragdrop-drop-functions '(dnd-target2))
    (set-extent-property ext 'mouse-face 'highlight)
    (insert "    ")
    (setq s (point))
    (insert "[ DROP TARGET 3]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'dragdrop-drop-functions '(dnd-target3))
    (set-extent-property ext 'mouse-face 'highlight)
    (newline 2)))

(defun make-drag-starters ()
  (let ((buf (get-buffer-create "*DND misc-user extent test buffer*"))
	(s nil)
	(e nil)
	(ext nil)
	(kmap nil))
    (set-buffer buf)
    (pop-to-buffer buf)
    (erase-buffer buf)
    (insert "Try to drag data from one of the upper extents to one\nof the lower extents. Make sure that your minibuffer is big\ncause it is used to display the data.\n\nYou may also try to select some of this text and drag it with button2.")
    (newline 2)
    (setq s (point))
    (insert "[ TEXT DRAG TEST ]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'mouse-face 'isearch)
    (setq kmap (make-keymap))
    (define-key kmap [button1] 'text-drag)
    (set-extent-property ext 'keymap kmap)
    (insert "    ")
    (setq s (point))
    (insert "[ FILE DRAG TEST ]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'mouse-face 'isearch)
    (setq kmap (make-keymap))
    (define-key kmap [button1] 'file-drag)
    (set-extent-property ext 'keymap kmap)
    (insert "    ")
    (setq s (point))
    (insert "[ FILES DRAG TEST ]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'mouse-face 'isearch)
    (setq kmap (make-keymap))
    (define-key kmap [button1] 'files-drag)
    (set-extent-property ext 'keymap kmap)
    (insert "    ")
    (setq s (point))
    (insert "[ URL DRAG TEST ]")
    (setq e (point))
    (setq ext (make-extent s e))
    (set-extent-property ext 'mouse-face 'isearch)
    (setq kmap (make-keymap))
    (define-key kmap [button1] 'url-drag)
    (set-extent-property ext 'keymap kmap)
    (newline 3)))
    
(defun text-drag (event)
  (interactive "@e")
  (offix-start-drag event "That's a test"))

(defun file-drag (event)
  (interactive "@e")
  (offix-start-drag event "/tmp/printcap" 2))

(defun url-drag (event)
  (interactive "@e")
  (offix-start-drag event "http://www.xemacs.org/" 8))

(defun files-drag (event)
  (interactive "@e")
  (offix-start-drag event '("/tmp/dragtest" "/tmp/droptest" "/tmp/printcap") 3))

(setq dragdrop-drop-functions '(do-nothing dnd-drop-somewhere do-nothing))
(make-drag-starters)
(make-drop-targets)
