(custom-put 'extensions 'custom-loads '("eldoc"))
(custom-put 'eldoc 'custom-loads '("eldoc"))
(custom-put 'minibuffer 'custom-loads '("detached-minibuf" "savehist"))
(custom-put 'mail 'custom-loads '("highlight-headers" "ph" "smtpmail"))
(custom-put 'uniquify 'custom-loads '("uniquify"))
(custom-put 'hypermedia 'custom-loads '("browse-url"))
(custom-put 'lisp 'custom-loads '("elp"))
(custom-put 'elp 'custom-loads '("elp"))
(custom-put 'applications 'custom-loads '("uniquify"))
(custom-put 'keyboard 'custom-loads '("edmacro"))
(custom-put 'crontab 'custom-loads '("crontab"))
(custom-put 'comm 'custom-loads '("ph"))
(custom-put 'id-select 'custom-loads '("id-select"))
(custom-put 'frames 'custom-loads '("detached-minibuf"))
(custom-put 'smtpmail 'custom-loads '("smtpmail"))
(custom-put 'detached-minibuf 'custom-loads '("detached-minibuf"))
(custom-put 'languages 'custom-loads '("crontab"))
(custom-put 'edmacro 'custom-loads '("edmacro"))
(custom-put 'faces 'custom-loads '("highlight-headers"))
(custom-put 'passwd 'custom-loads '("passwd"))
(custom-put 'browse-url 'custom-loads '("browse-url"))
(custom-put 'processes 'custom-loads '("passwd"))
(custom-put 'news 'custom-loads '("highlight-headers"))
(custom-put 'highlight-headers 'custom-loads '("highlight-headers"))
(custom-put 'savehist 'custom-loads '("savehist"))
(custom-put 'ph 'custom-loads '("ph"))
