;;; quail/lrt.el --- Quail package for inputting Lao characters by LRT method

;; Copyright (C) 1997 Free Software Foundation, Inc.
;; Copyright (C) 1997 Electrotechnical Laboratory, JAPAN.

;; Keywords: multilingual, input method, Lao, LRT.

;; This file is part of GNU Emacs.

;; GNU Emacs is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

;;; Code:

(require 'quail)
(require 'language/lao-util)

(defconst lrt-consonant-table
  '(("k" . "(1!(B")
    ("kh" . "(1"(B")
    ("qh" . "(1$(B")
    ("ng" . "(1'(B")
    ("j" . "(1((B")
    ("s" . "(1J(B")
    ("x" . "(1*(B")
    ("y" . "(1-(B")
    ("d" . "(14(B")
    ("t" . "(15(B")
    ("th" . "(16(B")
    ("dh" . "(17(B")
    ("n" . "(19(B")
    ("b" . "(1:(B")
    ("p" . "(1;(B")
    ("hp" . "(1<(B")
    ("fh" . "(1=(B")
    ("ph" . "(1>(B")
    ("f" . "(1?(B")
    ("m" . "(1A(B")
    ("gn" . "(1B(B")
    ("l" . "(1E(B")
    ("r" . "(1C(B")
    ("v" . "(1G(B")
    ("w" . "(1G(B")
    ("hh" . "(1K(B")
    ("O" . "(1M(B")
    ("h" . "(1N(B")
    ("ngh" . "(1K'(B")
    ("yh" . "(1K](B")
    ("nh" . "(1|(B")
    ("mh" . "(1}(B")
    ("lh" . "0(1K\1(B")

    ("wh" . "(1KG(B")
    ("hl" . "(1KE(B")
    ("hy" . "(1K-(B")         
    ("hn" . "(1K9(B")
    ("hm" . "(1KA(B")
    ))
               
(defconst lrt-vowel-table
  '(("a" (0 ?(1P(B) (0 ?(1Q(B))
    ("ar" (0 ?(1R(B))
    ("i" (0 ?(1T(B))
    ("ii" (0 ?(1U(B))
    ("eu" (0 ?(1V(B))
    ("ur" (0 ?(1W(B))
    ("u" (0 ?(1X(B))
    ("uu" (0 ?(1Y(B))
    ("e" (1 ?(1`(B ?(1P(B) (1 ?(1`(B ?(1Q(B))
    ("ee" (1 ?(1`(B))
    ("ae" (1 ?(1a(B ?(1P(B) (1 ?(1a(B ?(1Q(B))
    ("aa" (1 ?(1a(B))
    ("o" (1 ?(1b(B ?(1P(B) (0 ?(1[(B) (?(1-(B 1 ?(1b(B ?(1Q(B) (?(1G(B 1 ?(1b(B ?(1Q(B))
    ("oo" (1 ?(1b(B))
    ("oe" (1 ?(1`(B ?(1R(B ?(1P(B) (0 ?(1Q(B ?(1M(B))
    ("or" (0 ?(1m(B) (0 ?(1M(B))
    ("er" (1 ?(1`(B ?(1T(B))
    ("ir" (1 ?(1`(B ?(1U(B))
    ("oua" (0 ?(1[(B ?(1G(B ?(1P(B) (0 ?(1Q(B ?(1G(B))
    ("ua" (0 ?(1[(B ?(1G(B) (0 ?(1G(B))
    ("ie" (1 ?(1`(B ?(1Q(B ?(1](B ?(1P(B) (0 ?(1Q(B ?(1](B))
    ("ia" (1 ?(1`(B ?(1Q(B ?(1](B) (0 ?(1](B))
    ("eua" (1 ?(1`(B ?(1V(B ?(1M(B))
    ("ea" (1 ?(1`(B ?(1W(B ?(1M(B))
    ("ai" (1 ?(1d(B))
    ("ei" (1 ?(1c(B))
    ("ow" (1 ?(1`(B ?(1[(B ?(1R(B))
    ("am" (0 ?(1S(B))))

(eval-when-compile

(defconst lrt-maa-sakod-table
  '(("k" . "(1!(B")
    ("ng" . "(1'(B")
    ("y" . "(1-(B")
    ("d" . "(14(B")
    ("n" . "(19(B")
    ("b" . "(1:(B")
    ("m" . "(1A(B")
    ("v" . "(1G(B")
    ("w" . "(1G(B")))

(defconst lrt-maa-sakod-alist
  (let ((map '(nil))
	(l lrt-maa-sakod-table))
    (while l
      (set-nested-alist (car (car l)) (cdr (car l)) map)
      (setq l (cdr l)))
    (cdr map)))

)

(defconst lrt-tone-table
  '(("'" . "(1h(B")
    ("\"" . "(1i(B")
    ("+" . "(1k(B")))

(defun lrt-cv-compose (components consonant)
  (let ((idx (car components))
	(i 0)
	len l)
    (setq components (cdr components))
    (setq len (length components))
    (while (< i len)
      (if (= i idx)
	  (if (memq (get-char-code-property (car components) 'phonetic-type)
		    '(vowel-upper vowel-lower tone))
	      (progn
		(setq l (cons (compose-string
			       (concat (char-to-string (sref consonant 0))
				       (char-to-string (car components))))
			      l))
		(if (> (chars-in-string consonant) 1)
		    (setq l (cons (substring consonant
					     (char-bytes (sref consonant 0)))
				  l))))
	    (setq l (cons consonant l))
	    (setq l (cons (char-to-string (car components)) l)))
	(setq l (cons (char-to-string (car components)) l)))
      (setq components (cdr components) i (1+ i)))
    (if (= i idx)
	(setq l (cons consonant l)))
    (apply 'concat (nreverse l))))

(defun make-lrt-table ()
  (insert "(quail-define-rules\n")
  (let ((l lrt-vowel-table))
    (while l
      (insert (format " (\"%s\" \"%s\")\n"
		      (car (car l))
		      (mapconcat 'char-to-string (cdr (car (cdr (car l)))) ""))
	      )
      (setq l (cdr l))))
   (let ((l lrt-consonant-table))
    (while l
      (let ((l-elt (car l)))
	(insert (format " (\"%s\" \"%s\")\n" (car l-elt) (cdr l-elt)))
	(let ((ll lrt-vowel-table))
	  (while ll
	    (let* ((ll-elt (car ll))
		   (lrt-cv (lrt-cv-compose (car (cdr ll-elt)) (cdr l-elt))))
	      (insert (format " (\"%s%s\" [\"%s\"])\n"
			      (car l-elt) (car ll-elt) lrt-cv))
	      (let ((lll lrt-maa-sakod-table))
		(while lll
		  (let ((lll-elt (car lll))
			(lrt-cv2 (if (nth 2 ll-elt)
				     (lrt-cv-compose (nth 2 ll-elt)
						     (cdr l-elt))
				   lrt-cv)))
		    (insert (format " (\"%s%s%s\" [\"%s%s\"])\n"
				    (car l-elt) (car ll-elt) (car lll-elt)
				    lrt-cv2 (cdr lll-elt))))
		  (setq lll (cdr lll))))
	      (setq ll (cdr ll)))))
	(setq l (cdr l)))))
  (insert " )\n"))

(defun make-lrt-table ()
  (insert "(quail-define-rules\n")
  (let ((l lrt-vowel-table))
    (while l
      (insert (format " (\"%s\" \"%s\")\n"
		      (car (car l))
		      (mapconcat 'char-to-string (cdr (car (cdr (car l)))) ""))
	      )
      (setq l (cdr l))))
   (let ((l lrt-consonant-table))
    (while l
      (let ((l-elt (car l)))
	(insert (format " (\"%s\" \"%s\")\n" (car l-elt) (cdr l-elt)))
	(let ((ll lrt-vowel-table))
	  (while ll
	    (let* ((ll-elt (car ll))
		   (lrt-cv (lrt-cv-compose (car (cdr ll-elt)) (cdr l-elt))))
	      (insert (format " (\"%s%s\" ([\"%s\"] . lrt-maa-sakod-table))\n"
			      (car l-elt) (car ll-elt) lrt-cv))
	      (setq ll (cdr ll)))))
	(setq l (cdr l)))))
  (insert " )\n"))

(defmacro lrt-quail-define-rules (&rest rules)
  (let ((map '(quail-map))
	rule)
    (while rules
      (setq rule (car rules) rules (cdr rules))
      (if (not (consp (car (cdr rule))))
	  (set-nested-alist (car rule) (car (cdr rule)) map)
	(let ((entry (lookup-nested-alist (car rule) map nil nil t)))
	  (if (null entry)
	      (set-nested-alist (car rule) (car (cdr rule)) map nil
				(symbol-value (cdr (cdr rule))))
	    (set-nested-alist (car rule) (car (cdr rule)) map nil
			      (append (symbol-value (cdr (cdr rule)))
				      (cdr entry)))))))
    `(quail-install-map ,map)))

(quail-define-package "quail-lrt" "Lao" "LRT" t
		      "Lao input method with LRT (Lao Roman Transcription)"
		      nil t nil nil nil nil t)

(lrt-quail-define-rules
 ("a" "(1P(B")
 ("ar" "(1R(B")
 ("i" "(1T(B")
 ("ii" "(1U(B")
 ("eu" "(1V(B")
 ("ur" "(1W(B")
 ("u" "(1X(B")
 ("uu" "(1Y(B")
 ("e" "(1`P(B")
 ("ee" "(1`(B")
 ("ae" "(1aP(B")
 ("aa" "(1a(B")
 ("o" "(1bP(B")
 ("oo" "(1b(B")
 ("oe" "(1`RP(B")
 ("or" "(1m(B")
 ("er" "(1`T(B")
 ("ir" "(1`U(B")
 ("oua" "(1[GP(B")
 ("ua" "(1[G(B")
 ("ie" "(1`Q]P(B")
 ("ia" "(1`Q](B")
 ("eua" "(1`VM(B")
 ("ea" "(1`WM(B")
 ("ai" "(1d(B")
 ("ei" "(1c(B")
 ("ow" "(1`[R(B")
 ("am" "(1S(B")
 ("k" "(1!(B")
 ("ka" (["(1!P(B"] . lrt-maa-sakod-alist))
 ("kar" (["(1!R(B"] . lrt-maa-sakod-alist))
 ("ki" (["0(1!T1(B"] . lrt-maa-sakod-alist))
 ("kii" (["0(1!U1(B"] . lrt-maa-sakod-alist))
 ("keu" (["0(1!V1(B"] . lrt-maa-sakod-alist))
 ("kur" (["0(1!W1(B"] . lrt-maa-sakod-alist))
 ("ku" (["0(1!X1(B"] . lrt-maa-sakod-alist))
 ("kuu" (["0(1!Y1(B"] . lrt-maa-sakod-alist))
 ("ke" (["(1`!P(B"] . lrt-maa-sakod-alist))
 ("kee" (["(1`!(B"] . lrt-maa-sakod-alist))
 ("kae" (["(1a!P(B"] . lrt-maa-sakod-alist))
 ("kaa" (["(1a!(B"] . lrt-maa-sakod-alist))
 ("ko" (["(1b!P(B"] . lrt-maa-sakod-alist))
 ("koo" (["(1b!(B"] . lrt-maa-sakod-alist))
 ("koe" (["(1`!RP(B"] . lrt-maa-sakod-alist))
 ("kor" (["0(1!m1(B"] . lrt-maa-sakod-alist))
 ("ker" (["(1`0!T1(B"] . lrt-maa-sakod-alist))
 ("kir" (["(1`0!U1(B"] . lrt-maa-sakod-alist))
 ("koua" (["0(1![1GP(B"] . lrt-maa-sakod-alist))
 ("kua" (["0(1![1G(B"] . lrt-maa-sakod-alist))
 ("kie" (["(1`0!Q1]P(B"] . lrt-maa-sakod-alist))
 ("kia" (["(1`0!Q1](B"] . lrt-maa-sakod-alist))
 ("keua" (["(1`0!V1M(B"] . lrt-maa-sakod-alist))
 ("kea" (["(1`0!W1M(B"] . lrt-maa-sakod-alist))
 ("kai" (["(1d!(B"] . lrt-maa-sakod-alist))
 ("kei" (["(1c!(B"] . lrt-maa-sakod-alist))
 ("kow" (["(1`0![1R(B"] . lrt-maa-sakod-alist))
 ("kam" (["(1!S(B"] . lrt-maa-sakod-alist))
 ("kh" "(1"(B")
 ("kha" (["(1"P(B"] . lrt-maa-sakod-alist))
 ("khar" (["(1"R(B"] . lrt-maa-sakod-alist))
 ("khi" (["0(1"T1(B"] . lrt-maa-sakod-alist))
 ("khii" (["0(1"U1(B"] . lrt-maa-sakod-alist))
 ("kheu" (["0(1"V1(B"] . lrt-maa-sakod-alist))
 ("khur" (["0(1"W1(B"] . lrt-maa-sakod-alist))
 ("khu" (["0(1"X1(B"] . lrt-maa-sakod-alist))
 ("khuu" (["0(1"Y1(B"] . lrt-maa-sakod-alist))
 ("khe" (["(1`"P(B"] . lrt-maa-sakod-alist))
 ("khee" (["(1`"(B"] . lrt-maa-sakod-alist))
 ("khae" (["(1a"P(B"] . lrt-maa-sakod-alist))
 ("khaa" (["(1a"(B"] . lrt-maa-sakod-alist))
 ("kho" (["(1b"P(B"] . lrt-maa-sakod-alist))
 ("khoo" (["(1b"(B"] . lrt-maa-sakod-alist))
 ("khoe" (["(1`"RP(B"] . lrt-maa-sakod-alist))
 ("khor" (["0(1"m1(B"] . lrt-maa-sakod-alist))
 ("kher" (["(1`0"T1(B"] . lrt-maa-sakod-alist))
 ("khir" (["(1`0"U1(B"] . lrt-maa-sakod-alist))
 ("khoua" (["0(1"[1GP(B"] . lrt-maa-sakod-alist))
 ("khua" (["0(1"[1G(B"] . lrt-maa-sakod-alist))
 ("khie" (["(1`0"Q1]P(B"] . lrt-maa-sakod-alist))
 ("khia" (["(1`0"Q1](B"] . lrt-maa-sakod-alist))
 ("kheua" (["(1`0"V1M(B"] . lrt-maa-sakod-alist))
 ("khea" (["(1`0"W1M(B"] . lrt-maa-sakod-alist))
 ("khai" (["(1d"(B"] . lrt-maa-sakod-alist))
 ("khei" (["(1c"(B"] . lrt-maa-sakod-alist))
 ("khow" (["(1`0"[1R(B"] . lrt-maa-sakod-alist))
 ("kham" (["(1"S(B"] . lrt-maa-sakod-alist))
 ("qh" "(1$(B")
 ("qha" (["(1$P(B"] . lrt-maa-sakod-alist))
 ("qhar" (["(1$R(B"] . lrt-maa-sakod-alist))
 ("qhi" (["0(1$T1(B"] . lrt-maa-sakod-alist))
 ("qhii" (["0(1$U1(B"] . lrt-maa-sakod-alist))
 ("qheu" (["0(1$V1(B"] . lrt-maa-sakod-alist))
 ("qhur" (["0(1$W1(B"] . lrt-maa-sakod-alist))
 ("qhu" (["0(1$X1(B"] . lrt-maa-sakod-alist))
 ("qhuu" (["0(1$Y1(B"] . lrt-maa-sakod-alist))
 ("qhe" (["(1`$P(B"] . lrt-maa-sakod-alist))
 ("qhee" (["(1`$(B"] . lrt-maa-sakod-alist))
 ("qhae" (["(1a$P(B"] . lrt-maa-sakod-alist))
 ("qhaa" (["(1a$(B"] . lrt-maa-sakod-alist))
 ("qho" (["(1b$P(B"] . lrt-maa-sakod-alist))
 ("qhoo" (["(1b$(B"] . lrt-maa-sakod-alist))
 ("qhoe" (["(1`$RP(B"] . lrt-maa-sakod-alist))
 ("qhor" (["0(1$m1(B"] . lrt-maa-sakod-alist))
 ("qher" (["(1`0$T1(B"] . lrt-maa-sakod-alist))
 ("qhir" (["(1`0$U1(B"] . lrt-maa-sakod-alist))
 ("qhoua" (["0(1$[1GP(B"] . lrt-maa-sakod-alist))
 ("qhua" (["0(1$[1G(B"] . lrt-maa-sakod-alist))
 ("qhie" (["(1`0$Q1]P(B"] . lrt-maa-sakod-alist))
 ("qhia" (["(1`0$Q1](B"] . lrt-maa-sakod-alist))
 ("qheua" (["(1`0$V1M(B"] . lrt-maa-sakod-alist))
 ("qhea" (["(1`0$W1M(B"] . lrt-maa-sakod-alist))
 ("qhai" (["(1d$(B"] . lrt-maa-sakod-alist))
 ("qhei" (["(1c$(B"] . lrt-maa-sakod-alist))
 ("qhow" (["(1`0$[1R(B"] . lrt-maa-sakod-alist))
 ("qham" (["(1$S(B"] . lrt-maa-sakod-alist))
 ("ng" "(1'(B")
 ("nga" (["(1'P(B"] . lrt-maa-sakod-alist))
 ("ngar" (["(1'R(B"] . lrt-maa-sakod-alist))
 ("ngi" (["0(1'T1(B"] . lrt-maa-sakod-alist))
 ("ngii" (["0(1'U1(B"] . lrt-maa-sakod-alist))
 ("ngeu" (["0(1'V1(B"] . lrt-maa-sakod-alist))
 ("ngur" (["0(1'W1(B"] . lrt-maa-sakod-alist))
 ("ngu" (["0(1'X1(B"] . lrt-maa-sakod-alist))
 ("nguu" (["0(1'Y1(B"] . lrt-maa-sakod-alist))
 ("nge" (["(1`'P(B"] . lrt-maa-sakod-alist))
 ("ngee" (["(1`'(B"] . lrt-maa-sakod-alist))
 ("ngae" (["(1a'P(B"] . lrt-maa-sakod-alist))
 ("ngaa" (["(1a'(B"] . lrt-maa-sakod-alist))
 ("ngo" (["(1b'P(B"] . lrt-maa-sakod-alist))
 ("ngoo" (["(1b'(B"] . lrt-maa-sakod-alist))
 ("ngoe" (["(1`'RP(B"] . lrt-maa-sakod-alist))
 ("ngor" (["0(1'm1(B"] . lrt-maa-sakod-alist))
 ("nger" (["(1`0'T1(B"] . lrt-maa-sakod-alist))
 ("ngir" (["(1`0'U1(B"] . lrt-maa-sakod-alist))
 ("ngoua" (["0(1'[1GP(B"] . lrt-maa-sakod-alist))
 ("ngua" (["0(1'[1G(B"] . lrt-maa-sakod-alist))
 ("ngie" (["(1`0'Q1]P(B"] . lrt-maa-sakod-alist))
 ("ngia" (["(1`0'Q1](B"] . lrt-maa-sakod-alist))
 ("ngeua" (["(1`0'V1M(B"] . lrt-maa-sakod-alist))
 ("ngea" (["(1`0'W1M(B"] . lrt-maa-sakod-alist))
 ("ngai" (["(1d'(B"] . lrt-maa-sakod-alist))
 ("ngei" (["(1c'(B"] . lrt-maa-sakod-alist))
 ("ngow" (["(1`0'[1R(B"] . lrt-maa-sakod-alist))
 ("ngam" (["(1'S(B"] . lrt-maa-sakod-alist))
 ("j" "(1((B")
 ("ja" (["(1(P(B"] . lrt-maa-sakod-alist))
 ("jar" (["(1(R(B"] . lrt-maa-sakod-alist))
 ("ji" (["0(1(T1(B"] . lrt-maa-sakod-alist))
 ("jii" (["0(1(U1(B"] . lrt-maa-sakod-alist))
 ("jeu" (["0(1(V1(B"] . lrt-maa-sakod-alist))
 ("jur" (["0(1(W1(B"] . lrt-maa-sakod-alist))
 ("ju" (["0(1(X1(B"] . lrt-maa-sakod-alist))
 ("juu" (["0(1(Y1(B"] . lrt-maa-sakod-alist))
 ("je" (["(1`(P(B"] . lrt-maa-sakod-alist))
 ("jee" (["(1`((B"] . lrt-maa-sakod-alist))
 ("jae" (["(1a(P(B"] . lrt-maa-sakod-alist))
 ("jaa" (["(1a((B"] . lrt-maa-sakod-alist))
 ("jo" (["(1b(P(B"] . lrt-maa-sakod-alist))
 ("joo" (["(1b((B"] . lrt-maa-sakod-alist))
 ("joe" (["(1`(RP(B"] . lrt-maa-sakod-alist))
 ("jor" (["0(1(m1(B"] . lrt-maa-sakod-alist))
 ("jer" (["(1`0(T1(B"] . lrt-maa-sakod-alist))
 ("jir" (["(1`0(U1(B"] . lrt-maa-sakod-alist))
 ("joua" (["0(1([1GP(B"] . lrt-maa-sakod-alist))
 ("jua" (["0(1([1G(B"] . lrt-maa-sakod-alist))
 ("jie" (["(1`0(Q1]P(B"] . lrt-maa-sakod-alist))
 ("jia" (["(1`0(Q1](B"] . lrt-maa-sakod-alist))
 ("jeua" (["(1`0(V1M(B"] . lrt-maa-sakod-alist))
 ("jea" (["(1`0(W1M(B"] . lrt-maa-sakod-alist))
 ("jai" (["(1d((B"] . lrt-maa-sakod-alist))
 ("jei" (["(1c((B"] . lrt-maa-sakod-alist))
 ("jow" (["(1`0([1R(B"] . lrt-maa-sakod-alist))
 ("jam" (["(1(S(B"] . lrt-maa-sakod-alist))
 ("s" "(1J(B")
 ("sa" (["(1JP(B"] . lrt-maa-sakod-alist))
 ("sar" (["(1JR(B"] . lrt-maa-sakod-alist))
 ("si" (["0(1JT1(B"] . lrt-maa-sakod-alist))
 ("sii" (["0(1JU1(B"] . lrt-maa-sakod-alist))
 ("seu" (["0(1JV1(B"] . lrt-maa-sakod-alist))
 ("sur" (["0(1JW1(B"] . lrt-maa-sakod-alist))
 ("su" (["0(1JX1(B"] . lrt-maa-sakod-alist))
 ("suu" (["0(1JY1(B"] . lrt-maa-sakod-alist))
 ("se" (["(1`JP(B"] . lrt-maa-sakod-alist))
 ("see" (["(1`J(B"] . lrt-maa-sakod-alist))
 ("sae" (["(1aJP(B"] . lrt-maa-sakod-alist))
 ("saa" (["(1aJ(B"] . lrt-maa-sakod-alist))
 ("so" (["(1bJP(B"] . lrt-maa-sakod-alist))
 ("soo" (["(1bJ(B"] . lrt-maa-sakod-alist))
 ("soe" (["(1`JRP(B"] . lrt-maa-sakod-alist))
 ("sor" (["0(1Jm1(B"] . lrt-maa-sakod-alist))
 ("ser" (["(1`0JT1(B"] . lrt-maa-sakod-alist))
 ("sir" (["(1`0JU1(B"] . lrt-maa-sakod-alist))
 ("soua" (["0(1J[1GP(B"] . lrt-maa-sakod-alist))
 ("sua" (["0(1J[1G(B"] . lrt-maa-sakod-alist))
 ("sie" (["(1`0JQ1]P(B"] . lrt-maa-sakod-alist))
 ("sia" (["(1`0JQ1](B"] . lrt-maa-sakod-alist))
 ("seua" (["(1`0JV1M(B"] . lrt-maa-sakod-alist))
 ("sea" (["(1`0JW1M(B"] . lrt-maa-sakod-alist))
 ("sai" (["(1dJ(B"] . lrt-maa-sakod-alist))
 ("sei" (["(1cJ(B"] . lrt-maa-sakod-alist))
 ("sow" (["(1`0J[1R(B"] . lrt-maa-sakod-alist))
 ("sam" (["(1JS(B"] . lrt-maa-sakod-alist))
 ("x" "(1*(B")
 ("xa" (["(1*P(B"] . lrt-maa-sakod-alist))
 ("xar" (["(1*R(B"] . lrt-maa-sakod-alist))
 ("xi" (["0(1*T1(B"] . lrt-maa-sakod-alist))
 ("xii" (["0(1*U1(B"] . lrt-maa-sakod-alist))
 ("xeu" (["0(1*V1(B"] . lrt-maa-sakod-alist))
 ("xur" (["0(1*W1(B"] . lrt-maa-sakod-alist))
 ("xu" (["0(1*X1(B"] . lrt-maa-sakod-alist))
 ("xuu" (["0(1*Y1(B"] . lrt-maa-sakod-alist))
 ("xe" (["(1`*P(B"] . lrt-maa-sakod-alist))
 ("xee" (["(1`*(B"] . lrt-maa-sakod-alist))
 ("xae" (["(1a*P(B"] . lrt-maa-sakod-alist))
 ("xaa" (["(1a*(B"] . lrt-maa-sakod-alist))
 ("xo" (["(1b*P(B"] . lrt-maa-sakod-alist))
 ("xoo" (["(1b*(B"] . lrt-maa-sakod-alist))
 ("xoe" (["(1`*RP(B"] . lrt-maa-sakod-alist))
 ("xor" (["0(1*m1(B"] . lrt-maa-sakod-alist))
 ("xer" (["(1`0*T1(B"] . lrt-maa-sakod-alist))
 ("xir" (["(1`0*U1(B"] . lrt-maa-sakod-alist))
 ("xoua" (["0(1*[1GP(B"] . lrt-maa-sakod-alist))
 ("xua" (["0(1*[1G(B"] . lrt-maa-sakod-alist))
 ("xie" (["(1`0*Q1]P(B"] . lrt-maa-sakod-alist))
 ("xia" (["(1`0*Q1](B"] . lrt-maa-sakod-alist))
 ("xeua" (["(1`0*V1M(B"] . lrt-maa-sakod-alist))
 ("xea" (["(1`0*W1M(B"] . lrt-maa-sakod-alist))
 ("xai" (["(1d*(B"] . lrt-maa-sakod-alist))
 ("xei" (["(1c*(B"] . lrt-maa-sakod-alist))
 ("xow" (["(1`0*[1R(B"] . lrt-maa-sakod-alist))
 ("xam" (["(1*S(B"] . lrt-maa-sakod-alist))
 ("y" "(1-(B")
 ("ya" (["(1-P(B"] . lrt-maa-sakod-alist))
 ("yar" (["(1-R(B"] . lrt-maa-sakod-alist))
 ("yi" (["0(1-T1(B"] . lrt-maa-sakod-alist))
 ("yii" (["0(1-U1(B"] . lrt-maa-sakod-alist))
 ("yeu" (["0(1-V1(B"] . lrt-maa-sakod-alist))
 ("yur" (["0(1-W1(B"] . lrt-maa-sakod-alist))
 ("yu" (["0(1-X1(B"] . lrt-maa-sakod-alist))
 ("yuu" (["0(1-Y1(B"] . lrt-maa-sakod-alist))
 ("ye" (["(1`-P(B"] . lrt-maa-sakod-alist))
 ("yee" (["(1`-(B"] . lrt-maa-sakod-alist))
 ("yae" (["(1a-P(B"] . lrt-maa-sakod-alist))
 ("yaa" (["(1a-(B"] . lrt-maa-sakod-alist))
 ("yo" (["(1b-P(B"] . lrt-maa-sakod-alist))
 ("yoo" (["(1b-(B"] . lrt-maa-sakod-alist))
 ("yoe" (["(1`-RP(B"] . lrt-maa-sakod-alist))
 ("yor" (["0(1-m1(B"] . lrt-maa-sakod-alist))
 ("yer" (["(1`0-T1(B"] . lrt-maa-sakod-alist))
 ("yir" (["(1`0-U1(B"] . lrt-maa-sakod-alist))
 ("youa" (["0(1-[1GP(B"] . lrt-maa-sakod-alist))
 ("yua" (["0(1-[1G(B"] . lrt-maa-sakod-alist))
 ("yie" (["(1`0-Q1]P(B"] . lrt-maa-sakod-alist))
 ("yia" (["(1`0-Q1](B"] . lrt-maa-sakod-alist))
 ("yeua" (["(1`0-V1M(B"] . lrt-maa-sakod-alist))
 ("yea" (["(1`0-W1M(B"] . lrt-maa-sakod-alist))
 ("yai" (["(1d-(B"] . lrt-maa-sakod-alist))
 ("yei" (["(1c-(B"] . lrt-maa-sakod-alist))
 ("yow" (["(1`0-[1R(B"] . lrt-maa-sakod-alist))
 ("yam" (["(1-S(B"] . lrt-maa-sakod-alist))
 ("d" "(14(B")
 ("da" (["(14P(B"] . lrt-maa-sakod-alist))
 ("dar" (["(14R(B"] . lrt-maa-sakod-alist))
 ("di" (["0(14T1(B"] . lrt-maa-sakod-alist))
 ("dii" (["0(14U1(B"] . lrt-maa-sakod-alist))
 ("deu" (["0(14V1(B"] . lrt-maa-sakod-alist))
 ("dur" (["0(14W1(B"] . lrt-maa-sakod-alist))
 ("du" (["0(14X1(B"] . lrt-maa-sakod-alist))
 ("duu" (["0(14Y1(B"] . lrt-maa-sakod-alist))
 ("de" (["(1`4P(B"] . lrt-maa-sakod-alist))
 ("dee" (["(1`4(B"] . lrt-maa-sakod-alist))
 ("dae" (["(1a4P(B"] . lrt-maa-sakod-alist))
 ("daa" (["(1a4(B"] . lrt-maa-sakod-alist))
 ("do" (["(1b4P(B"] . lrt-maa-sakod-alist))
 ("doo" (["(1b4(B"] . lrt-maa-sakod-alist))
 ("doe" (["(1`4RP(B"] . lrt-maa-sakod-alist))
 ("dor" (["0(14m1(B"] . lrt-maa-sakod-alist))
 ("der" (["(1`04T1(B"] . lrt-maa-sakod-alist))
 ("dir" (["(1`04U1(B"] . lrt-maa-sakod-alist))
 ("doua" (["0(14[1GP(B"] . lrt-maa-sakod-alist))
 ("dua" (["0(14[1G(B"] . lrt-maa-sakod-alist))
 ("die" (["(1`04Q1]P(B"] . lrt-maa-sakod-alist))
 ("dia" (["(1`04Q1](B"] . lrt-maa-sakod-alist))
 ("deua" (["(1`04V1M(B"] . lrt-maa-sakod-alist))
 ("dea" (["(1`04W1M(B"] . lrt-maa-sakod-alist))
 ("dai" (["(1d4(B"] . lrt-maa-sakod-alist))
 ("dei" (["(1c4(B"] . lrt-maa-sakod-alist))
 ("dow" (["(1`04[1R(B"] . lrt-maa-sakod-alist))
 ("dam" (["(14S(B"] . lrt-maa-sakod-alist))
 ("t" "(15(B")
 ("ta" (["(15P(B"] . lrt-maa-sakod-alist))
 ("tar" (["(15R(B"] . lrt-maa-sakod-alist))
 ("ti" (["0(15T1(B"] . lrt-maa-sakod-alist))
 ("tii" (["0(15U1(B"] . lrt-maa-sakod-alist))
 ("teu" (["0(15V1(B"] . lrt-maa-sakod-alist))
 ("tur" (["0(15W1(B"] . lrt-maa-sakod-alist))
 ("tu" (["0(15X1(B"] . lrt-maa-sakod-alist))
 ("tuu" (["0(15Y1(B"] . lrt-maa-sakod-alist))
 ("te" (["(1`5P(B"] . lrt-maa-sakod-alist))
 ("tee" (["(1`5(B"] . lrt-maa-sakod-alist))
 ("tae" (["(1a5P(B"] . lrt-maa-sakod-alist))
 ("taa" (["(1a5(B"] . lrt-maa-sakod-alist))
 ("to" (["(1b5P(B"] . lrt-maa-sakod-alist))
 ("too" (["(1b5(B"] . lrt-maa-sakod-alist))
 ("toe" (["(1`5RP(B"] . lrt-maa-sakod-alist))
 ("tor" (["0(15m1(B"] . lrt-maa-sakod-alist))
 ("ter" (["(1`05T1(B"] . lrt-maa-sakod-alist))
 ("tir" (["(1`05U1(B"] . lrt-maa-sakod-alist))
 ("toua" (["0(15[1GP(B"] . lrt-maa-sakod-alist))
 ("tua" (["0(15[1G(B"] . lrt-maa-sakod-alist))
 ("tie" (["(1`05Q1]P(B"] . lrt-maa-sakod-alist))
 ("tia" (["(1`05Q1](B"] . lrt-maa-sakod-alist))
 ("teua" (["(1`05V1M(B"] . lrt-maa-sakod-alist))
 ("tea" (["(1`05W1M(B"] . lrt-maa-sakod-alist))
 ("tai" (["(1d5(B"] . lrt-maa-sakod-alist))
 ("tei" (["(1c5(B"] . lrt-maa-sakod-alist))
 ("tow" (["(1`05[1R(B"] . lrt-maa-sakod-alist))
 ("tam" (["(15S(B"] . lrt-maa-sakod-alist))
 ("th" "(16(B")
 ("tha" (["(16P(B"] . lrt-maa-sakod-alist))
 ("thar" (["(16R(B"] . lrt-maa-sakod-alist))
 ("thi" (["0(16T1(B"] . lrt-maa-sakod-alist))
 ("thii" (["0(16U1(B"] . lrt-maa-sakod-alist))
 ("theu" (["0(16V1(B"] . lrt-maa-sakod-alist))
 ("thur" (["0(16W1(B"] . lrt-maa-sakod-alist))
 ("thu" (["0(16X1(B"] . lrt-maa-sakod-alist))
 ("thuu" (["0(16Y1(B"] . lrt-maa-sakod-alist))
 ("the" (["(1`6P(B"] . lrt-maa-sakod-alist))
 ("thee" (["(1`6(B"] . lrt-maa-sakod-alist))
 ("thae" (["(1a6P(B"] . lrt-maa-sakod-alist))
 ("thaa" (["(1a6(B"] . lrt-maa-sakod-alist))
 ("tho" (["(1b6P(B"] . lrt-maa-sakod-alist))
 ("thoo" (["(1b6(B"] . lrt-maa-sakod-alist))
 ("thoe" (["(1`6RP(B"] . lrt-maa-sakod-alist))
 ("thor" (["0(16m1(B"] . lrt-maa-sakod-alist))
 ("ther" (["(1`06T1(B"] . lrt-maa-sakod-alist))
 ("thir" (["(1`06U1(B"] . lrt-maa-sakod-alist))
 ("thoua" (["0(16[1GP(B"] . lrt-maa-sakod-alist))
 ("thua" (["0(16[1G(B"] . lrt-maa-sakod-alist))
 ("thie" (["(1`06Q1]P(B"] . lrt-maa-sakod-alist))
 ("thia" (["(1`06Q1](B"] . lrt-maa-sakod-alist))
 ("theua" (["(1`06V1M(B"] . lrt-maa-sakod-alist))
 ("thea" (["(1`06W1M(B"] . lrt-maa-sakod-alist))
 ("thai" (["(1d6(B"] . lrt-maa-sakod-alist))
 ("thei" (["(1c6(B"] . lrt-maa-sakod-alist))
 ("thow" (["(1`06[1R(B"] . lrt-maa-sakod-alist))
 ("tham" (["(16S(B"] . lrt-maa-sakod-alist))
 ("dh" "(17(B")
 ("dha" (["(17P(B"] . lrt-maa-sakod-alist))
 ("dhar" (["(17R(B"] . lrt-maa-sakod-alist))
 ("dhi" (["0(17T1(B"] . lrt-maa-sakod-alist))
 ("dhii" (["0(17U1(B"] . lrt-maa-sakod-alist))
 ("dheu" (["0(17V1(B"] . lrt-maa-sakod-alist))
 ("dhur" (["0(17W1(B"] . lrt-maa-sakod-alist))
 ("dhu" (["0(17X1(B"] . lrt-maa-sakod-alist))
 ("dhuu" (["0(17Y1(B"] . lrt-maa-sakod-alist))
 ("dhe" (["(1`7P(B"] . lrt-maa-sakod-alist))
 ("dhee" (["(1`7(B"] . lrt-maa-sakod-alist))
 ("dhae" (["(1a7P(B"] . lrt-maa-sakod-alist))
 ("dhaa" (["(1a7(B"] . lrt-maa-sakod-alist))
 ("dho" (["(1b7P(B"] . lrt-maa-sakod-alist))
 ("dhoo" (["(1b7(B"] . lrt-maa-sakod-alist))
 ("dhoe" (["(1`7RP(B"] . lrt-maa-sakod-alist))
 ("dhor" (["0(17m1(B"] . lrt-maa-sakod-alist))
 ("dher" (["(1`07T1(B"] . lrt-maa-sakod-alist))
 ("dhir" (["(1`07U1(B"] . lrt-maa-sakod-alist))
 ("dhoua" (["0(17[1GP(B"] . lrt-maa-sakod-alist))
 ("dhua" (["0(17[1G(B"] . lrt-maa-sakod-alist))
 ("dhie" (["(1`07Q1]P(B"] . lrt-maa-sakod-alist))
 ("dhia" (["(1`07Q1](B"] . lrt-maa-sakod-alist))
 ("dheua" (["(1`07V1M(B"] . lrt-maa-sakod-alist))
 ("dhea" (["(1`07W1M(B"] . lrt-maa-sakod-alist))
 ("dhai" (["(1d7(B"] . lrt-maa-sakod-alist))
 ("dhei" (["(1c7(B"] . lrt-maa-sakod-alist))
 ("dhow" (["(1`07[1R(B"] . lrt-maa-sakod-alist))
 ("dham" (["(17S(B"] . lrt-maa-sakod-alist))
 ("n" "(19(B")
 ("na" (["(19P(B"] . lrt-maa-sakod-alist))
 ("nar" (["(19R(B"] . lrt-maa-sakod-alist))
 ("ni" (["0(19T1(B"] . lrt-maa-sakod-alist))
 ("nii" (["0(19U1(B"] . lrt-maa-sakod-alist))
 ("neu" (["0(19V1(B"] . lrt-maa-sakod-alist))
 ("nur" (["0(19W1(B"] . lrt-maa-sakod-alist))
 ("nu" (["0(19X1(B"] . lrt-maa-sakod-alist))
 ("nuu" (["0(19Y1(B"] . lrt-maa-sakod-alist))
 ("ne" (["(1`9P(B"] . lrt-maa-sakod-alist))
 ("nee" (["(1`9(B"] . lrt-maa-sakod-alist))
 ("nae" (["(1a9P(B"] . lrt-maa-sakod-alist))
 ("naa" (["(1a9(B"] . lrt-maa-sakod-alist))
 ("no" (["(1b9P(B"] . lrt-maa-sakod-alist))
 ("noo" (["(1b9(B"] . lrt-maa-sakod-alist))
 ("noe" (["(1`9RP(B"] . lrt-maa-sakod-alist))
 ("nor" (["0(19m1(B"] . lrt-maa-sakod-alist))
 ("ner" (["(1`09T1(B"] . lrt-maa-sakod-alist))
 ("nir" (["(1`09U1(B"] . lrt-maa-sakod-alist))
 ("noua" (["0(19[1GP(B"] . lrt-maa-sakod-alist))
 ("nua" (["0(19[1G(B"] . lrt-maa-sakod-alist))
 ("nie" (["(1`09Q1]P(B"] . lrt-maa-sakod-alist))
 ("nia" (["(1`09Q1](B"] . lrt-maa-sakod-alist))
 ("neua" (["(1`09V1M(B"] . lrt-maa-sakod-alist))
 ("nea" (["(1`09W1M(B"] . lrt-maa-sakod-alist))
 ("nai" (["(1d9(B"] . lrt-maa-sakod-alist))
 ("nei" (["(1c9(B"] . lrt-maa-sakod-alist))
 ("now" (["(1`09[1R(B"] . lrt-maa-sakod-alist))
 ("nam" (["(19S(B"] . lrt-maa-sakod-alist))
 ("b" "(1:(B")
 ("ba" (["(1:P(B"] . lrt-maa-sakod-alist))
 ("bar" (["(1:R(B"] . lrt-maa-sakod-alist))
 ("bi" (["0(1:T1(B"] . lrt-maa-sakod-alist))
 ("bii" (["0(1:U1(B"] . lrt-maa-sakod-alist))
 ("beu" (["0(1:V1(B"] . lrt-maa-sakod-alist))
 ("bur" (["0(1:W1(B"] . lrt-maa-sakod-alist))
 ("bu" (["0(1:X1(B"] . lrt-maa-sakod-alist))
 ("buu" (["0(1:Y1(B"] . lrt-maa-sakod-alist))
 ("be" (["(1`:P(B"] . lrt-maa-sakod-alist))
 ("bee" (["(1`:(B"] . lrt-maa-sakod-alist))
 ("bae" (["(1a:P(B"] . lrt-maa-sakod-alist))
 ("baa" (["(1a:(B"] . lrt-maa-sakod-alist))
 ("bo" (["(1b:P(B"] . lrt-maa-sakod-alist))
 ("boo" (["(1b:(B"] . lrt-maa-sakod-alist))
 ("boe" (["(1`:RP(B"] . lrt-maa-sakod-alist))
 ("bor" (["0(1:m1(B"] . lrt-maa-sakod-alist))
 ("ber" (["(1`0:T1(B"] . lrt-maa-sakod-alist))
 ("bir" (["(1`0:U1(B"] . lrt-maa-sakod-alist))
 ("boua" (["0(1:[1GP(B"] . lrt-maa-sakod-alist))
 ("bua" (["0(1:[1G(B"] . lrt-maa-sakod-alist))
 ("bie" (["(1`0:Q1]P(B"] . lrt-maa-sakod-alist))
 ("bia" (["(1`0:Q1](B"] . lrt-maa-sakod-alist))
 ("beua" (["(1`0:V1M(B"] . lrt-maa-sakod-alist))
 ("bea" (["(1`0:W1M(B"] . lrt-maa-sakod-alist))
 ("bai" (["(1d:(B"] . lrt-maa-sakod-alist))
 ("bei" (["(1c:(B"] . lrt-maa-sakod-alist))
 ("bow" (["(1`0:[1R(B"] . lrt-maa-sakod-alist))
 ("bam" (["(1:S(B"] . lrt-maa-sakod-alist))
 ("p" "(1;(B")
 ("pa" (["(1;P(B"] . lrt-maa-sakod-alist))
 ("par" (["(1;R(B"] . lrt-maa-sakod-alist))
 ("pi" (["0(1;T1(B"] . lrt-maa-sakod-alist))
 ("pii" (["0(1;U1(B"] . lrt-maa-sakod-alist))
 ("peu" (["0(1;V1(B"] . lrt-maa-sakod-alist))
 ("pur" (["0(1;W1(B"] . lrt-maa-sakod-alist))
 ("pu" (["0(1;X1(B"] . lrt-maa-sakod-alist))
 ("puu" (["0(1;Y1(B"] . lrt-maa-sakod-alist))
 ("pe" (["(1`;P(B"] . lrt-maa-sakod-alist))
 ("pee" (["(1`;(B"] . lrt-maa-sakod-alist))
 ("pae" (["(1a;P(B"] . lrt-maa-sakod-alist))
 ("paa" (["(1a;(B"] . lrt-maa-sakod-alist))
 ("po" (["(1b;P(B"] . lrt-maa-sakod-alist))
 ("poo" (["(1b;(B"] . lrt-maa-sakod-alist))
 ("poe" (["(1`;RP(B"] . lrt-maa-sakod-alist))
 ("por" (["0(1;m1(B"] . lrt-maa-sakod-alist))
 ("per" (["(1`0;T1(B"] . lrt-maa-sakod-alist))
 ("pir" (["(1`0;U1(B"] . lrt-maa-sakod-alist))
 ("poua" (["0(1;[1GP(B"] . lrt-maa-sakod-alist))
 ("pua" (["0(1;[1G(B"] . lrt-maa-sakod-alist))
 ("pie" (["(1`0;Q1]P(B"] . lrt-maa-sakod-alist))
 ("pia" (["(1`0;Q1](B"] . lrt-maa-sakod-alist))
 ("peua" (["(1`0;V1M(B"] . lrt-maa-sakod-alist))
 ("pea" (["(1`0;W1M(B"] . lrt-maa-sakod-alist))
 ("pai" (["(1d;(B"] . lrt-maa-sakod-alist))
 ("pei" (["(1c;(B"] . lrt-maa-sakod-alist))
 ("pow" (["(1`0;[1R(B"] . lrt-maa-sakod-alist))
 ("pam" (["(1;S(B"] . lrt-maa-sakod-alist))
 ("hp" "(1<(B")
 ("hpa" (["(1<P(B"] . lrt-maa-sakod-alist))
 ("hpar" (["(1<R(B"] . lrt-maa-sakod-alist))
 ("hpi" (["0(1<T1(B"] . lrt-maa-sakod-alist))
 ("hpii" (["0(1<U1(B"] . lrt-maa-sakod-alist))
 ("hpeu" (["0(1<V1(B"] . lrt-maa-sakod-alist))
 ("hpur" (["0(1<W1(B"] . lrt-maa-sakod-alist))
 ("hpu" (["0(1<X1(B"] . lrt-maa-sakod-alist))
 ("hpuu" (["0(1<Y1(B"] . lrt-maa-sakod-alist))
 ("hpe" (["(1`<P(B"] . lrt-maa-sakod-alist))
 ("hpee" (["(1`<(B"] . lrt-maa-sakod-alist))
 ("hpae" (["(1a<P(B"] . lrt-maa-sakod-alist))
 ("hpaa" (["(1a<(B"] . lrt-maa-sakod-alist))
 ("hpo" (["(1b<P(B"] . lrt-maa-sakod-alist))
 ("hpoo" (["(1b<(B"] . lrt-maa-sakod-alist))
 ("hpoe" (["(1`<RP(B"] . lrt-maa-sakod-alist))
 ("hpor" (["0(1<m1(B"] . lrt-maa-sakod-alist))
 ("hper" (["(1`0<T1(B"] . lrt-maa-sakod-alist))
 ("hpir" (["(1`0<U1(B"] . lrt-maa-sakod-alist))
 ("hpoua" (["0(1<[1GP(B"] . lrt-maa-sakod-alist))
 ("hpua" (["0(1<[1G(B"] . lrt-maa-sakod-alist))
 ("hpie" (["(1`0<Q1]P(B"] . lrt-maa-sakod-alist))
 ("hpia" (["(1`0<Q1](B"] . lrt-maa-sakod-alist))
 ("hpeua" (["(1`0<V1M(B"] . lrt-maa-sakod-alist))
 ("hpea" (["(1`0<W1M(B"] . lrt-maa-sakod-alist))
 ("hpai" (["(1d<(B"] . lrt-maa-sakod-alist))
 ("hpei" (["(1c<(B"] . lrt-maa-sakod-alist))
 ("hpow" (["(1`0<[1R(B"] . lrt-maa-sakod-alist))
 ("hpam" (["(1<S(B"] . lrt-maa-sakod-alist))
 ("fh" "(1=(B")
 ("fha" (["(1=P(B"] . lrt-maa-sakod-alist))
 ("fhar" (["(1=R(B"] . lrt-maa-sakod-alist))
 ("fhi" (["0(1=T1(B"] . lrt-maa-sakod-alist))
 ("fhii" (["0(1=U1(B"] . lrt-maa-sakod-alist))
 ("fheu" (["0(1=V1(B"] . lrt-maa-sakod-alist))
 ("fhur" (["0(1=W1(B"] . lrt-maa-sakod-alist))
 ("fhu" (["0(1=X1(B"] . lrt-maa-sakod-alist))
 ("fhuu" (["0(1=Y1(B"] . lrt-maa-sakod-alist))
 ("fhe" (["(1`=P(B"] . lrt-maa-sakod-alist))
 ("fhee" (["(1`=(B"] . lrt-maa-sakod-alist))
 ("fhae" (["(1a=P(B"] . lrt-maa-sakod-alist))
 ("fhaa" (["(1a=(B"] . lrt-maa-sakod-alist))
 ("fho" (["(1b=P(B"] . lrt-maa-sakod-alist))
 ("fhoo" (["(1b=(B"] . lrt-maa-sakod-alist))
 ("fhoe" (["(1`=RP(B"] . lrt-maa-sakod-alist))
 ("fhor" (["0(1=m1(B"] . lrt-maa-sakod-alist))
 ("fher" (["(1`0=T1(B"] . lrt-maa-sakod-alist))
 ("fhir" (["(1`0=U1(B"] . lrt-maa-sakod-alist))
 ("fhoua" (["0(1=[1GP(B"] . lrt-maa-sakod-alist))
 ("fhua" (["0(1=[1G(B"] . lrt-maa-sakod-alist))
 ("fhie" (["(1`0=Q1]P(B"] . lrt-maa-sakod-alist))
 ("fhia" (["(1`0=Q1](B"] . lrt-maa-sakod-alist))
 ("fheua" (["(1`0=V1M(B"] . lrt-maa-sakod-alist))
 ("fhea" (["(1`0=W1M(B"] . lrt-maa-sakod-alist))
 ("fhai" (["(1d=(B"] . lrt-maa-sakod-alist))
 ("fhei" (["(1c=(B"] . lrt-maa-sakod-alist))
 ("fhow" (["(1`0=[1R(B"] . lrt-maa-sakod-alist))
 ("fham" (["(1=S(B"] . lrt-maa-sakod-alist))
 ("ph" "(1>(B")
 ("pha" (["(1>P(B"] . lrt-maa-sakod-alist))
 ("phar" (["(1>R(B"] . lrt-maa-sakod-alist))
 ("phi" (["0(1>T1(B"] . lrt-maa-sakod-alist))
 ("phii" (["0(1>U1(B"] . lrt-maa-sakod-alist))
 ("pheu" (["0(1>V1(B"] . lrt-maa-sakod-alist))
 ("phur" (["0(1>W1(B"] . lrt-maa-sakod-alist))
 ("phu" (["0(1>X1(B"] . lrt-maa-sakod-alist))
 ("phuu" (["0(1>Y1(B"] . lrt-maa-sakod-alist))
 ("phe" (["(1`>P(B"] . lrt-maa-sakod-alist))
 ("phee" (["(1`>(B"] . lrt-maa-sakod-alist))
 ("phae" (["(1a>P(B"] . lrt-maa-sakod-alist))
 ("phaa" (["(1a>(B"] . lrt-maa-sakod-alist))
 ("pho" (["(1b>P(B"] . lrt-maa-sakod-alist))
 ("phoo" (["(1b>(B"] . lrt-maa-sakod-alist))
 ("phoe" (["(1`>RP(B"] . lrt-maa-sakod-alist))
 ("phor" (["0(1>m1(B"] . lrt-maa-sakod-alist))
 ("pher" (["(1`0>T1(B"] . lrt-maa-sakod-alist))
 ("phir" (["(1`0>U1(B"] . lrt-maa-sakod-alist))
 ("phoua" (["0(1>[1GP(B"] . lrt-maa-sakod-alist))
 ("phua" (["0(1>[1G(B"] . lrt-maa-sakod-alist))
 ("phie" (["(1`0>Q1]P(B"] . lrt-maa-sakod-alist))
 ("phia" (["(1`0>Q1](B"] . lrt-maa-sakod-alist))
 ("pheua" (["(1`0>V1M(B"] . lrt-maa-sakod-alist))
 ("phea" (["(1`0>W1M(B"] . lrt-maa-sakod-alist))
 ("phai" (["(1d>(B"] . lrt-maa-sakod-alist))
 ("phei" (["(1c>(B"] . lrt-maa-sakod-alist))
 ("phow" (["(1`0>[1R(B"] . lrt-maa-sakod-alist))
 ("pham" (["(1>S(B"] . lrt-maa-sakod-alist))
 ("f" "(1?(B")
 ("fa" (["(1?P(B"] . lrt-maa-sakod-alist))
 ("far" (["(1?R(B"] . lrt-maa-sakod-alist))
 ("fi" (["0(1?T1(B"] . lrt-maa-sakod-alist))
 ("fii" (["0(1?U1(B"] . lrt-maa-sakod-alist))
 ("feu" (["0(1?V1(B"] . lrt-maa-sakod-alist))
 ("fur" (["0(1?W1(B"] . lrt-maa-sakod-alist))
 ("fu" (["0(1?X1(B"] . lrt-maa-sakod-alist))
 ("fuu" (["0(1?Y1(B"] . lrt-maa-sakod-alist))
 ("fe" (["(1`?P(B"] . lrt-maa-sakod-alist))
 ("fee" (["(1`?(B"] . lrt-maa-sakod-alist))
 ("fae" (["(1a?P(B"] . lrt-maa-sakod-alist))
 ("faa" (["(1a?(B"] . lrt-maa-sakod-alist))
 ("fo" (["(1b?P(B"] . lrt-maa-sakod-alist))
 ("foo" (["(1b?(B"] . lrt-maa-sakod-alist))
 ("foe" (["(1`?RP(B"] . lrt-maa-sakod-alist))
 ("for" (["0(1?m1(B"] . lrt-maa-sakod-alist))
 ("fer" (["(1`0?T1(B"] . lrt-maa-sakod-alist))
 ("fir" (["(1`0?U1(B"] . lrt-maa-sakod-alist))
 ("foua" (["0(1?[1GP(B"] . lrt-maa-sakod-alist))
 ("fua" (["0(1?[1G(B"] . lrt-maa-sakod-alist))
 ("fie" (["(1`0?Q1]P(B"] . lrt-maa-sakod-alist))
 ("fia" (["(1`0?Q1](B"] . lrt-maa-sakod-alist))
 ("feua" (["(1`0?V1M(B"] . lrt-maa-sakod-alist))
 ("fea" (["(1`0?W1M(B"] . lrt-maa-sakod-alist))
 ("fai" (["(1d?(B"] . lrt-maa-sakod-alist))
 ("fei" (["(1c?(B"] . lrt-maa-sakod-alist))
 ("fow" (["(1`0?[1R(B"] . lrt-maa-sakod-alist))
 ("fam" (["(1?S(B"] . lrt-maa-sakod-alist))
 ("m" "(1A(B")
 ("ma" (["(1AP(B"] . lrt-maa-sakod-alist))
 ("mar" (["(1AR(B"] . lrt-maa-sakod-alist))
 ("mi" (["0(1AT1(B"] . lrt-maa-sakod-alist))
 ("mii" (["0(1AU1(B"] . lrt-maa-sakod-alist))
 ("meu" (["0(1AV1(B"] . lrt-maa-sakod-alist))
 ("mur" (["0(1AW1(B"] . lrt-maa-sakod-alist))
 ("mu" (["0(1AX1(B"] . lrt-maa-sakod-alist))
 ("muu" (["0(1AY1(B"] . lrt-maa-sakod-alist))
 ("me" (["(1`AP(B"] . lrt-maa-sakod-alist))
 ("mee" (["(1`A(B"] . lrt-maa-sakod-alist))
 ("mae" (["(1aAP(B"] . lrt-maa-sakod-alist))
 ("maa" (["(1aA(B"] . lrt-maa-sakod-alist))
 ("mo" (["(1bAP(B"] . lrt-maa-sakod-alist))
 ("moo" (["(1bA(B"] . lrt-maa-sakod-alist))
 ("moe" (["(1`ARP(B"] . lrt-maa-sakod-alist))
 ("mor" (["0(1Am1(B"] . lrt-maa-sakod-alist))
 ("mer" (["(1`0AT1(B"] . lrt-maa-sakod-alist))
 ("mir" (["(1`0AU1(B"] . lrt-maa-sakod-alist))
 ("moua" (["0(1A[1GP(B"] . lrt-maa-sakod-alist))
 ("mua" (["0(1A[1G(B"] . lrt-maa-sakod-alist))
 ("mie" (["(1`0AQ1]P(B"] . lrt-maa-sakod-alist))
 ("mia" (["(1`0AQ1](B"] . lrt-maa-sakod-alist))
 ("meua" (["(1`0AV1M(B"] . lrt-maa-sakod-alist))
 ("mea" (["(1`0AW1M(B"] . lrt-maa-sakod-alist))
 ("mai" (["(1dA(B"] . lrt-maa-sakod-alist))
 ("mei" (["(1cA(B"] . lrt-maa-sakod-alist))
 ("mow" (["(1`0A[1R(B"] . lrt-maa-sakod-alist))
 ("mam" (["(1AS(B"] . lrt-maa-sakod-alist))
 ("gn" "(1B(B")
 ("gna" (["(1BP(B"] . lrt-maa-sakod-alist))
 ("gnar" (["(1BR(B"] . lrt-maa-sakod-alist))
 ("gni" (["0(1BT1(B"] . lrt-maa-sakod-alist))
 ("gnii" (["0(1BU1(B"] . lrt-maa-sakod-alist))
 ("gneu" (["0(1BV1(B"] . lrt-maa-sakod-alist))
 ("gnur" (["0(1BW1(B"] . lrt-maa-sakod-alist))
 ("gnu" (["0(1BX1(B"] . lrt-maa-sakod-alist))
 ("gnuu" (["0(1BY1(B"] . lrt-maa-sakod-alist))
 ("gne" (["(1`BP(B"] . lrt-maa-sakod-alist))
 ("gnee" (["(1`B(B"] . lrt-maa-sakod-alist))
 ("gnae" (["(1aBP(B"] . lrt-maa-sakod-alist))
 ("gnaa" (["(1aB(B"] . lrt-maa-sakod-alist))
 ("gno" (["(1bBP(B"] . lrt-maa-sakod-alist))
 ("gnoo" (["(1bB(B"] . lrt-maa-sakod-alist))
 ("gnoe" (["(1`BRP(B"] . lrt-maa-sakod-alist))
 ("gnor" (["0(1Bm1(B"] . lrt-maa-sakod-alist))
 ("gner" (["(1`0BT1(B"] . lrt-maa-sakod-alist))
 ("gnir" (["(1`0BU1(B"] . lrt-maa-sakod-alist))
 ("gnoua" (["0(1B[1GP(B"] . lrt-maa-sakod-alist))
 ("gnua" (["0(1B[1G(B"] . lrt-maa-sakod-alist))
 ("gnie" (["(1`0BQ1]P(B"] . lrt-maa-sakod-alist))
 ("gnia" (["(1`0BQ1](B"] . lrt-maa-sakod-alist))
 ("gneua" (["(1`0BV1M(B"] . lrt-maa-sakod-alist))
 ("gnea" (["(1`0BW1M(B"] . lrt-maa-sakod-alist))
 ("gnai" (["(1dB(B"] . lrt-maa-sakod-alist))
 ("gnei" (["(1cB(B"] . lrt-maa-sakod-alist))
 ("gnow" (["(1`0B[1R(B"] . lrt-maa-sakod-alist))
 ("gnam" (["(1BS(B"] . lrt-maa-sakod-alist))
 ("l" "(1E(B")
 ("la" (["(1EP(B"] . lrt-maa-sakod-alist))
 ("lar" (["(1ER(B"] . lrt-maa-sakod-alist))
 ("li" (["0(1ET1(B"] . lrt-maa-sakod-alist))
 ("lii" (["0(1EU1(B"] . lrt-maa-sakod-alist))
 ("leu" (["0(1EV1(B"] . lrt-maa-sakod-alist))
 ("lur" (["0(1EW1(B"] . lrt-maa-sakod-alist))
 ("lu" (["0(1EX1(B"] . lrt-maa-sakod-alist))
 ("luu" (["0(1EY1(B"] . lrt-maa-sakod-alist))
 ("le" (["(1`EP(B"] . lrt-maa-sakod-alist))
 ("lee" (["(1`E(B"] . lrt-maa-sakod-alist))
 ("lae" (["(1aEP(B"] . lrt-maa-sakod-alist))
 ("laa" (["(1aE(B"] . lrt-maa-sakod-alist))
 ("lo" (["(1bEP(B"] . lrt-maa-sakod-alist))
 ("loo" (["(1bE(B"] . lrt-maa-sakod-alist))
 ("loe" (["(1`ERP(B"] . lrt-maa-sakod-alist))
 ("lor" (["0(1Em1(B"] . lrt-maa-sakod-alist))
 ("ler" (["(1`0ET1(B"] . lrt-maa-sakod-alist))
 ("lir" (["(1`0EU1(B"] . lrt-maa-sakod-alist))
 ("loua" (["0(1E[1GP(B"] . lrt-maa-sakod-alist))
 ("lua" (["0(1E[1G(B"] . lrt-maa-sakod-alist))
 ("lie" (["(1`0EQ1]P(B"] . lrt-maa-sakod-alist))
 ("lia" (["(1`0EQ1](B"] . lrt-maa-sakod-alist))
 ("leua" (["(1`0EV1M(B"] . lrt-maa-sakod-alist))
 ("lea" (["(1`0EW1M(B"] . lrt-maa-sakod-alist))
 ("lai" (["(1dE(B"] . lrt-maa-sakod-alist))
 ("lei" (["(1cE(B"] . lrt-maa-sakod-alist))
 ("low" (["(1`0E[1R(B"] . lrt-maa-sakod-alist))
 ("lam" (["(1ES(B"] . lrt-maa-sakod-alist))
 ("r" "(1C(B")
 ("ra" (["(1CP(B"] . lrt-maa-sakod-alist))
 ("rar" (["(1CR(B"] . lrt-maa-sakod-alist))
 ("ri" (["0(1CT1(B"] . lrt-maa-sakod-alist))
 ("rii" (["0(1CU1(B"] . lrt-maa-sakod-alist))
 ("reu" (["0(1CV1(B"] . lrt-maa-sakod-alist))
 ("rur" (["0(1CW1(B"] . lrt-maa-sakod-alist))
 ("ru" (["0(1CX1(B"] . lrt-maa-sakod-alist))
 ("ruu" (["0(1CY1(B"] . lrt-maa-sakod-alist))
 ("re" (["(1`CP(B"] . lrt-maa-sakod-alist))
 ("ree" (["(1`C(B"] . lrt-maa-sakod-alist))
 ("rae" (["(1aCP(B"] . lrt-maa-sakod-alist))
 ("raa" (["(1aC(B"] . lrt-maa-sakod-alist))
 ("ro" (["(1bCP(B"] . lrt-maa-sakod-alist))
 ("roo" (["(1bC(B"] . lrt-maa-sakod-alist))
 ("roe" (["(1`CRP(B"] . lrt-maa-sakod-alist))
 ("ror" (["0(1Cm1(B"] . lrt-maa-sakod-alist))
 ("rer" (["(1`0CT1(B"] . lrt-maa-sakod-alist))
 ("rir" (["(1`0CU1(B"] . lrt-maa-sakod-alist))
 ("roua" (["0(1C[1GP(B"] . lrt-maa-sakod-alist))
 ("rua" (["0(1C[1G(B"] . lrt-maa-sakod-alist))
 ("rie" (["(1`0CQ1]P(B"] . lrt-maa-sakod-alist))
 ("ria" (["(1`0CQ1](B"] . lrt-maa-sakod-alist))
 ("reua" (["(1`0CV1M(B"] . lrt-maa-sakod-alist))
 ("rea" (["(1`0CW1M(B"] . lrt-maa-sakod-alist))
 ("rai" (["(1dC(B"] . lrt-maa-sakod-alist))
 ("rei" (["(1cC(B"] . lrt-maa-sakod-alist))
 ("row" (["(1`0C[1R(B"] . lrt-maa-sakod-alist))
 ("ram" (["(1CS(B"] . lrt-maa-sakod-alist))
 ("v" "(1G(B")
 ("va" (["(1GP(B"] . lrt-maa-sakod-alist))
 ("var" (["(1GR(B"] . lrt-maa-sakod-alist))
 ("vi" (["0(1GT1(B"] . lrt-maa-sakod-alist))
 ("vii" (["0(1GU1(B"] . lrt-maa-sakod-alist))
 ("veu" (["0(1GV1(B"] . lrt-maa-sakod-alist))
 ("vur" (["0(1GW1(B"] . lrt-maa-sakod-alist))
 ("vu" (["0(1GX1(B"] . lrt-maa-sakod-alist))
 ("vuu" (["0(1GY1(B"] . lrt-maa-sakod-alist))
 ("ve" (["(1`GP(B"] . lrt-maa-sakod-alist))
 ("vee" (["(1`G(B"] . lrt-maa-sakod-alist))
 ("vae" (["(1aGP(B"] . lrt-maa-sakod-alist))
 ("vaa" (["(1aG(B"] . lrt-maa-sakod-alist))
 ("vo" (["(1bGP(B"] . lrt-maa-sakod-alist))
 ("voo" (["(1bG(B"] . lrt-maa-sakod-alist))
 ("voe" (["(1`GRP(B"] . lrt-maa-sakod-alist))
 ("vor" (["0(1Gm1(B"] . lrt-maa-sakod-alist))
 ("ver" (["(1`0GT1(B"] . lrt-maa-sakod-alist))
 ("vir" (["(1`0GU1(B"] . lrt-maa-sakod-alist))
 ("voua" (["0(1G[1GP(B"] . lrt-maa-sakod-alist))
 ("vua" (["0(1G[1G(B"] . lrt-maa-sakod-alist))
 ("vie" (["(1`0GQ1]P(B"] . lrt-maa-sakod-alist))
 ("via" (["(1`0GQ1](B"] . lrt-maa-sakod-alist))
 ("veua" (["(1`0GV1M(B"] . lrt-maa-sakod-alist))
 ("vea" (["(1`0GW1M(B"] . lrt-maa-sakod-alist))
 ("vai" (["(1dG(B"] . lrt-maa-sakod-alist))
 ("vei" (["(1cG(B"] . lrt-maa-sakod-alist))
 ("vow" (["(1`0G[1R(B"] . lrt-maa-sakod-alist))
 ("vam" (["(1GS(B"] . lrt-maa-sakod-alist))
 ("w" "(1G(B")
 ("wa" (["(1GP(B"] . lrt-maa-sakod-alist))
 ("war" (["(1GR(B"] . lrt-maa-sakod-alist))
 ("wi" (["0(1GT1(B"] . lrt-maa-sakod-alist))
 ("wii" (["0(1GU1(B"] . lrt-maa-sakod-alist))
 ("weu" (["0(1GV1(B"] . lrt-maa-sakod-alist))
 ("wur" (["0(1GW1(B"] . lrt-maa-sakod-alist))
 ("wu" (["0(1GX1(B"] . lrt-maa-sakod-alist))
 ("wuu" (["0(1GY1(B"] . lrt-maa-sakod-alist))
 ("we" (["(1`GP(B"] . lrt-maa-sakod-alist))
 ("wee" (["(1`G(B"] . lrt-maa-sakod-alist))
 ("wae" (["(1aGP(B"] . lrt-maa-sakod-alist))
 ("waa" (["(1aG(B"] . lrt-maa-sakod-alist))
 ("wo" (["(1bGP(B"] . lrt-maa-sakod-alist))
 ("woo" (["(1bG(B"] . lrt-maa-sakod-alist))
 ("woe" (["(1`GRP(B"] . lrt-maa-sakod-alist))
 ("wor" (["0(1Gm1(B"] . lrt-maa-sakod-alist))
 ("wer" (["(1`0GT1(B"] . lrt-maa-sakod-alist))
 ("wir" (["(1`0GU1(B"] . lrt-maa-sakod-alist))
 ("woua" (["0(1G[1GP(B"] . lrt-maa-sakod-alist))
 ("wua" (["0(1G[1G(B"] . lrt-maa-sakod-alist))
 ("wie" (["(1`0GQ1]P(B"] . lrt-maa-sakod-alist))
 ("wia" (["(1`0GQ1](B"] . lrt-maa-sakod-alist))
 ("weua" (["(1`0GV1M(B"] . lrt-maa-sakod-alist))
 ("wea" (["(1`0GW1M(B"] . lrt-maa-sakod-alist))
 ("wai" (["(1dG(B"] . lrt-maa-sakod-alist))
 ("wei" (["(1cG(B"] . lrt-maa-sakod-alist))
 ("wow" (["(1`0G[1R(B"] . lrt-maa-sakod-alist))
 ("wam" (["(1GS(B"] . lrt-maa-sakod-alist))
 ("hh" "(1K(B")
 ("hha" (["(1KP(B"] . lrt-maa-sakod-alist))
 ("hhar" (["(1KR(B"] . lrt-maa-sakod-alist))
 ("hhi" (["0(1KT1(B"] . lrt-maa-sakod-alist))
 ("hhii" (["0(1KU1(B"] . lrt-maa-sakod-alist))
 ("hheu" (["0(1KV1(B"] . lrt-maa-sakod-alist))
 ("hhur" (["0(1KW1(B"] . lrt-maa-sakod-alist))
 ("hhu" (["0(1KX1(B"] . lrt-maa-sakod-alist))
 ("hhuu" (["0(1KY1(B"] . lrt-maa-sakod-alist))
 ("hhe" (["(1`KP(B"] . lrt-maa-sakod-alist))
 ("hhee" (["(1`K(B"] . lrt-maa-sakod-alist))
 ("hhae" (["(1aKP(B"] . lrt-maa-sakod-alist))
 ("hhaa" (["(1aK(B"] . lrt-maa-sakod-alist))
 ("hho" (["(1bKP(B"] . lrt-maa-sakod-alist))
 ("hhoo" (["(1bK(B"] . lrt-maa-sakod-alist))
 ("hhoe" (["(1`KRP(B"] . lrt-maa-sakod-alist))
 ("hhor" (["0(1Km1(B"] . lrt-maa-sakod-alist))
 ("hher" (["(1`0KT1(B"] . lrt-maa-sakod-alist))
 ("hhir" (["(1`0KU1(B"] . lrt-maa-sakod-alist))
 ("hhoua" (["0(1K[1GP(B"] . lrt-maa-sakod-alist))
 ("hhua" (["0(1K[1G(B"] . lrt-maa-sakod-alist))
 ("hhie" (["(1`0KQ1]P(B"] . lrt-maa-sakod-alist))
 ("hhia" (["(1`0KQ1](B"] . lrt-maa-sakod-alist))
 ("hheua" (["(1`0KV1M(B"] . lrt-maa-sakod-alist))
 ("hhea" (["(1`0KW1M(B"] . lrt-maa-sakod-alist))
 ("hhai" (["(1dK(B"] . lrt-maa-sakod-alist))
 ("hhei" (["(1cK(B"] . lrt-maa-sakod-alist))
 ("hhow" (["(1`0K[1R(B"] . lrt-maa-sakod-alist))
 ("hham" (["(1KS(B"] . lrt-maa-sakod-alist))
 ("O" "(1M(B")
 ("Oa" (["(1MP(B"] . lrt-maa-sakod-alist))
 ("Oar" (["(1MR(B"] . lrt-maa-sakod-alist))
 ("Oi" (["0(1MT1(B"] . lrt-maa-sakod-alist))
 ("Oii" (["0(1MU1(B"] . lrt-maa-sakod-alist))
 ("Oeu" (["0(1MV1(B"] . lrt-maa-sakod-alist))
 ("Our" (["0(1MW1(B"] . lrt-maa-sakod-alist))
 ("Ou" (["0(1MX1(B"] . lrt-maa-sakod-alist))
 ("Ouu" (["0(1MY1(B"] . lrt-maa-sakod-alist))
 ("Oe" (["(1`MP(B"] . lrt-maa-sakod-alist))
 ("Oee" (["(1`M(B"] . lrt-maa-sakod-alist))
 ("Oae" (["(1aMP(B"] . lrt-maa-sakod-alist))
 ("Oaa" (["(1aM(B"] . lrt-maa-sakod-alist))
 ("Oo" (["(1bMP(B"] . lrt-maa-sakod-alist))
 ("Ooo" (["(1bM(B"] . lrt-maa-sakod-alist))
 ("Ooe" (["(1`MRP(B"] . lrt-maa-sakod-alist))
 ("Oor" (["0(1Mm1(B"] . lrt-maa-sakod-alist))
 ("Oer" (["(1`0MT1(B"] . lrt-maa-sakod-alist))
 ("Oir" (["(1`0MU1(B"] . lrt-maa-sakod-alist))
 ("Ooua" (["0(1M[1GP(B"] . lrt-maa-sakod-alist))
 ("Oua" (["0(1M[1G(B"] . lrt-maa-sakod-alist))
 ("Oie" (["(1`0MQ1]P(B"] . lrt-maa-sakod-alist))
 ("Oia" (["(1`0MQ1](B"] . lrt-maa-sakod-alist))
 ("Oeua" (["(1`0MV1M(B"] . lrt-maa-sakod-alist))
 ("Oea" (["(1`0MW1M(B"] . lrt-maa-sakod-alist))
 ("Oai" (["(1dM(B"] . lrt-maa-sakod-alist))
 ("Oei" (["(1cM(B"] . lrt-maa-sakod-alist))
 ("Oow" (["(1`0M[1R(B"] . lrt-maa-sakod-alist))
 ("Oam" (["(1MS(B"] . lrt-maa-sakod-alist))
 ("h" "(1N(B")
 ("ha" (["(1NP(B"] . lrt-maa-sakod-alist))
 ("har" (["(1NR(B"] . lrt-maa-sakod-alist))
 ("hi" (["0(1NT1(B"] . lrt-maa-sakod-alist))
 ("hii" (["0(1NU1(B"] . lrt-maa-sakod-alist))
 ("heu" (["0(1NV1(B"] . lrt-maa-sakod-alist))
 ("hur" (["0(1NW1(B"] . lrt-maa-sakod-alist))
 ("hu" (["0(1NX1(B"] . lrt-maa-sakod-alist))
 ("huu" (["0(1NY1(B"] . lrt-maa-sakod-alist))
 ("he" (["(1`NP(B"] . lrt-maa-sakod-alist))
 ("hee" (["(1`N(B"] . lrt-maa-sakod-alist))
 ("hae" (["(1aNP(B"] . lrt-maa-sakod-alist))
 ("haa" (["(1aN(B"] . lrt-maa-sakod-alist))
 ("ho" (["(1bNP(B"] . lrt-maa-sakod-alist))
 ("hoo" (["(1bN(B"] . lrt-maa-sakod-alist))
 ("hoe" (["(1`NRP(B"] . lrt-maa-sakod-alist))
 ("hor" (["0(1Nm1(B"] . lrt-maa-sakod-alist))
 ("her" (["(1`0NT1(B"] . lrt-maa-sakod-alist))
 ("hir" (["(1`0NU1(B"] . lrt-maa-sakod-alist))
 ("houa" (["0(1N[1GP(B"] . lrt-maa-sakod-alist))
 ("hua" (["0(1N[1G(B"] . lrt-maa-sakod-alist))
 ("hie" (["(1`0NQ1]P(B"] . lrt-maa-sakod-alist))
 ("hia" (["(1`0NQ1](B"] . lrt-maa-sakod-alist))
 ("heua" (["(1`0NV1M(B"] . lrt-maa-sakod-alist))
 ("hea" (["(1`0NW1M(B"] . lrt-maa-sakod-alist))
 ("hai" (["(1dN(B"] . lrt-maa-sakod-alist))
 ("hei" (["(1cN(B"] . lrt-maa-sakod-alist))
 ("how" (["(1`0N[1R(B"] . lrt-maa-sakod-alist))
 ("ham" (["(1NS(B"] . lrt-maa-sakod-alist))
 ("ngh" "(1K'(B")
 ("ngha" (["(1K'P(B"] . lrt-maa-sakod-alist))
 ("nghar" (["(1K'R(B"] . lrt-maa-sakod-alist))
 ("nghi" (["0(1KT1'(B"] . lrt-maa-sakod-alist))
 ("nghii" (["0(1KU1'(B"] . lrt-maa-sakod-alist))
 ("ngheu" (["0(1KV1'(B"] . lrt-maa-sakod-alist))
 ("nghur" (["0(1KW1'(B"] . lrt-maa-sakod-alist))
 ("nghu" (["0(1KX1'(B"] . lrt-maa-sakod-alist))
 ("nghuu" (["0(1KY1'(B"] . lrt-maa-sakod-alist))
 ("nghe" (["(1`K'P(B"] . lrt-maa-sakod-alist))
 ("nghee" (["(1`K'(B"] . lrt-maa-sakod-alist))
 ("nghae" (["(1aK'P(B"] . lrt-maa-sakod-alist))
 ("nghaa" (["(1aK'(B"] . lrt-maa-sakod-alist))
 ("ngho" (["(1bK'P(B"] . lrt-maa-sakod-alist))
 ("nghoo" (["(1bK'(B"] . lrt-maa-sakod-alist))
 ("nghoe" (["(1`K'RP(B"] . lrt-maa-sakod-alist))
 ("nghor" (["0(1Km1'(B"] . lrt-maa-sakod-alist))
 ("ngher" (["(1`0KT1'(B"] . lrt-maa-sakod-alist))
 ("nghir" (["(1`0KU1'(B"] . lrt-maa-sakod-alist))
 ("nghoua" (["0(1K[1'GP(B"] . lrt-maa-sakod-alist))
 ("nghua" (["0(1K[1'G(B"] . lrt-maa-sakod-alist))
 ("nghie" (["(1`0KQ1']P(B"] . lrt-maa-sakod-alist))
 ("nghia" (["(1`0KQ1'](B"] . lrt-maa-sakod-alist))
 ("ngheua" (["(1`0KV1'M(B"] . lrt-maa-sakod-alist))
 ("nghea" (["(1`0KW1'M(B"] . lrt-maa-sakod-alist))
 ("nghai" (["(1dK'(B"] . lrt-maa-sakod-alist))
 ("nghei" (["(1cK'(B"] . lrt-maa-sakod-alist))
 ("nghow" (["(1`0K[1'R(B"] . lrt-maa-sakod-alist))
 ("ngham" (["(1K'S(B"] . lrt-maa-sakod-alist))
 ("yh" "(1K](B")
 ("yha" (["(1K]P(B"] . lrt-maa-sakod-alist))
 ("yhar" (["(1K]R(B"] . lrt-maa-sakod-alist))
 ("yhi" (["0(1KT1](B"] . lrt-maa-sakod-alist))
 ("yhii" (["0(1KU1](B"] . lrt-maa-sakod-alist))
 ("yheu" (["0(1KV1](B"] . lrt-maa-sakod-alist))
 ("yhur" (["0(1KW1](B"] . lrt-maa-sakod-alist))
 ("yhu" (["0(1KX1](B"] . lrt-maa-sakod-alist))
 ("yhuu" (["0(1KY1](B"] . lrt-maa-sakod-alist))
 ("yhe" (["(1`K]P(B"] . lrt-maa-sakod-alist))
 ("yhee" (["(1`K](B"] . lrt-maa-sakod-alist))
 ("yhae" (["(1aK]P(B"] . lrt-maa-sakod-alist))
 ("yhaa" (["(1aK](B"] . lrt-maa-sakod-alist))
 ("yho" (["(1bK]P(B"] . lrt-maa-sakod-alist))
 ("yhoo" (["(1bK](B"] . lrt-maa-sakod-alist))
 ("yhoe" (["(1`K]RP(B"] . lrt-maa-sakod-alist))
 ("yhor" (["0(1Km1](B"] . lrt-maa-sakod-alist))
 ("yher" (["(1`0KT1](B"] . lrt-maa-sakod-alist))
 ("yhir" (["(1`0KU1](B"] . lrt-maa-sakod-alist))
 ("yhoua" (["0(1K[1]GP(B"] . lrt-maa-sakod-alist))
 ("yhua" (["0(1K[1]G(B"] . lrt-maa-sakod-alist))
 ("yhie" (["(1`0KQ1]]P(B"] . lrt-maa-sakod-alist))
 ("yhia" (["(1`0KQ1]](B"] . lrt-maa-sakod-alist))
 ("yheua" (["(1`0KV1]M(B"] . lrt-maa-sakod-alist))
 ("yhea" (["(1`0KW1]M(B"] . lrt-maa-sakod-alist))
 ("yhai" (["(1dK](B"] . lrt-maa-sakod-alist))
 ("yhei" (["(1cK](B"] . lrt-maa-sakod-alist))
 ("yhow" (["(1`0K[1]R(B"] . lrt-maa-sakod-alist))
 ("yham" (["(1K]S(B"] . lrt-maa-sakod-alist))
 ("nh" "(1|(B")
 ("nha" (["(1|P(B"] . lrt-maa-sakod-alist))
 ("nhar" (["(1|R(B"] . lrt-maa-sakod-alist))
 ("nhi" (["0(1|T1(B"] . lrt-maa-sakod-alist))
 ("nhii" (["0(1|U1(B"] . lrt-maa-sakod-alist))
 ("nheu" (["0(1|V1(B"] . lrt-maa-sakod-alist))
 ("nhur" (["0(1|W1(B"] . lrt-maa-sakod-alist))
 ("nhu" (["0(1|X1(B"] . lrt-maa-sakod-alist))
 ("nhuu" (["0(1|Y1(B"] . lrt-maa-sakod-alist))
 ("nhe" (["(1`|P(B"] . lrt-maa-sakod-alist))
 ("nhee" (["(1`|(B"] . lrt-maa-sakod-alist))
 ("nhae" (["(1a|P(B"] . lrt-maa-sakod-alist))
 ("nhaa" (["(1a|(B"] . lrt-maa-sakod-alist))
 ("nho" (["(1b|P(B"] . lrt-maa-sakod-alist))
 ("nhoo" (["(1b|(B"] . lrt-maa-sakod-alist))
 ("nhoe" (["(1`|RP(B"] . lrt-maa-sakod-alist))
 ("nhor" (["0(1|m1(B"] . lrt-maa-sakod-alist))
 ("nher" (["(1`0|T1(B"] . lrt-maa-sakod-alist))
 ("nhir" (["(1`0|U1(B"] . lrt-maa-sakod-alist))
 ("nhoua" (["0(1|[1GP(B"] . lrt-maa-sakod-alist))
 ("nhua" (["0(1|[1G(B"] . lrt-maa-sakod-alist))
 ("nhie" (["(1`0|Q1]P(B"] . lrt-maa-sakod-alist))
 ("nhia" (["(1`0|Q1](B"] . lrt-maa-sakod-alist))
 ("nheua" (["(1`0|V1M(B"] . lrt-maa-sakod-alist))
 ("nhea" (["(1`0|W1M(B"] . lrt-maa-sakod-alist))
 ("nhai" (["(1d|(B"] . lrt-maa-sakod-alist))
 ("nhei" (["(1c|(B"] . lrt-maa-sakod-alist))
 ("nhow" (["(1`0|[1R(B"] . lrt-maa-sakod-alist))
 ("nham" (["(1|S(B"] . lrt-maa-sakod-alist))
 ("mh" "(1}(B")
 ("mha" (["(1}P(B"] . lrt-maa-sakod-alist))
 ("mhar" (["(1}R(B"] . lrt-maa-sakod-alist))
 ("mhi" (["0(1}T1(B"] . lrt-maa-sakod-alist))
 ("mhii" (["0(1}U1(B"] . lrt-maa-sakod-alist))
 ("mheu" (["0(1}V1(B"] . lrt-maa-sakod-alist))
 ("mhur" (["0(1}W1(B"] . lrt-maa-sakod-alist))
 ("mhu" (["0(1}X1(B"] . lrt-maa-sakod-alist))
 ("mhuu" (["0(1}Y1(B"] . lrt-maa-sakod-alist))
 ("mhe" (["(1`}P(B"] . lrt-maa-sakod-alist))
 ("mhee" (["(1`}(B"] . lrt-maa-sakod-alist))
 ("mhae" (["(1a}P(B"] . lrt-maa-sakod-alist))
 ("mhaa" (["(1a}(B"] . lrt-maa-sakod-alist))
 ("mho" (["(1b}P(B"] . lrt-maa-sakod-alist))
 ("mhoo" (["(1b}(B"] . lrt-maa-sakod-alist))
 ("mhoe" (["(1`}RP(B"] . lrt-maa-sakod-alist))
 ("mhor" (["0(1}m1(B"] . lrt-maa-sakod-alist))
 ("mher" (["(1`0}T1(B"] . lrt-maa-sakod-alist))
 ("mhir" (["(1`0}U1(B"] . lrt-maa-sakod-alist))
 ("mhoua" (["0(1}[1GP(B"] . lrt-maa-sakod-alist))
 ("mhua" (["0(1}[1G(B"] . lrt-maa-sakod-alist))
 ("mhie" (["(1`0}Q1]P(B"] . lrt-maa-sakod-alist))
 ("mhia" (["(1`0}Q1](B"] . lrt-maa-sakod-alist))
 ("mheua" (["(1`0}V1M(B"] . lrt-maa-sakod-alist))
 ("mhea" (["(1`0}W1M(B"] . lrt-maa-sakod-alist))
 ("mhai" (["(1d}(B"] . lrt-maa-sakod-alist))
 ("mhei" (["(1c}(B"] . lrt-maa-sakod-alist))
 ("mhow" (["(1`0}[1R(B"] . lrt-maa-sakod-alist))
 ("mham" (["(1}S(B"] . lrt-maa-sakod-alist))
 ("lh" "0(1K\1(B")
 ("lha" (["0(1K\1P(B"] . lrt-maa-sakod-alist))
 ("lhar" (["0(1K\1R(B"] . lrt-maa-sakod-alist))
 ("lhi" (["0(1K\T1(B"] . lrt-maa-sakod-alist))
 ("lhii" (["0(1K\U1(B"] . lrt-maa-sakod-alist))
 ("lheu" (["0(1K\V1(B"] . lrt-maa-sakod-alist))
 ("lhur" (["0(1K\W1(B"] . lrt-maa-sakod-alist))
 ("lhu" (["0(1K\X1(B"] . lrt-maa-sakod-alist))
 ("lhuu" (["0(1K\Y1(B"] . lrt-maa-sakod-alist))
 ("lhe" (["(1`0K\1P(B"] . lrt-maa-sakod-alist))
 ("lhee" (["(1`0K\1(B"] . lrt-maa-sakod-alist))
 ("lhae" (["(1a0K\1P(B"] . lrt-maa-sakod-alist))
 ("lhaa" (["(1a0K\1(B"] . lrt-maa-sakod-alist))
 ("lho" (["(1b0K\1P(B"] . lrt-maa-sakod-alist))
 ("lhoo" (["(1b0K\1(B"] . lrt-maa-sakod-alist))
 ("lhoe" (["(1`0K\1RP(B"] . lrt-maa-sakod-alist))
 ("lhor" (["0(1K\m1(B"] . lrt-maa-sakod-alist))
 ("lher" (["(1`0K\T1(B"] . lrt-maa-sakod-alist))
 ("lhir" (["(1`0K\U1(B"] . lrt-maa-sakod-alist))
 ("lhoua" (["0(1K\[1GP(B"] . lrt-maa-sakod-alist))
 ("lhua" (["0(1K\[1G(B"] . lrt-maa-sakod-alist))
 ("lhie" (["(1`0K\Q1]P(B"] . lrt-maa-sakod-alist))
 ("lhia" (["(1`0K\Q1](B"] . lrt-maa-sakod-alist))
 ("lheua" (["(1`0K\V1M(B"] . lrt-maa-sakod-alist))
 ("lhea" (["(1`0K\W1M(B"] . lrt-maa-sakod-alist))
 ("lhai" (["(1d0K\1(B"] . lrt-maa-sakod-alist))
 ("lhei" (["(1c0K\1(B"] . lrt-maa-sakod-alist))
 ("lhow" (["(1`0K\[1R(B"] . lrt-maa-sakod-alist))
 ("lham" (["0(1K\1S(B"] . lrt-maa-sakod-alist))
 ("wh" "(1KG(B")
 ("wha" (["(1KGP(B"] . lrt-maa-sakod-alist))
 ("whar" (["(1KGR(B"] . lrt-maa-sakod-alist))
 ("whi" (["0(1KT1G(B"] . lrt-maa-sakod-alist))
 ("whii" (["0(1KU1G(B"] . lrt-maa-sakod-alist))
 ("wheu" (["0(1KV1G(B"] . lrt-maa-sakod-alist))
 ("whur" (["0(1KW1G(B"] . lrt-maa-sakod-alist))
 ("whu" (["0(1KX1G(B"] . lrt-maa-sakod-alist))
 ("whuu" (["0(1KY1G(B"] . lrt-maa-sakod-alist))
 ("whe" (["(1`KGP(B"] . lrt-maa-sakod-alist))
 ("whee" (["(1`KG(B"] . lrt-maa-sakod-alist))
 ("whae" (["(1aKGP(B"] . lrt-maa-sakod-alist))
 ("whaa" (["(1aKG(B"] . lrt-maa-sakod-alist))
 ("who" (["(1bKGP(B"] . lrt-maa-sakod-alist))
 ("whoo" (["(1bKG(B"] . lrt-maa-sakod-alist))
 ("whoe" (["(1`KGRP(B"] . lrt-maa-sakod-alist))
 ("whor" (["0(1Km1G(B"] . lrt-maa-sakod-alist))
 ("wher" (["(1`0KT1G(B"] . lrt-maa-sakod-alist))
 ("whir" (["(1`0KU1G(B"] . lrt-maa-sakod-alist))
 ("whoua" (["0(1K[1GGP(B"] . lrt-maa-sakod-alist))
 ("whua" (["0(1K[1GG(B"] . lrt-maa-sakod-alist))
 ("whie" (["(1`0KQ1G]P(B"] . lrt-maa-sakod-alist))
 ("whia" (["(1`0KQ1G](B"] . lrt-maa-sakod-alist))
 ("wheua" (["(1`0KV1GM(B"] . lrt-maa-sakod-alist))
 ("whea" (["(1`0KW1GM(B"] . lrt-maa-sakod-alist))
 ("whai" (["(1dKG(B"] . lrt-maa-sakod-alist))
 ("whei" (["(1cKG(B"] . lrt-maa-sakod-alist))
 ("whow" (["(1`0K[1GR(B"] . lrt-maa-sakod-alist))
 ("wham" (["(1KGS(B"] . lrt-maa-sakod-alist))
 ("hl" "(1KE(B")
 ("hla" (["(1KEP(B"] . lrt-maa-sakod-alist))
 ("hlar" (["(1KER(B"] . lrt-maa-sakod-alist))
 ("hli" (["0(1KT1E(B"] . lrt-maa-sakod-alist))
 ("hlii" (["0(1KU1E(B"] . lrt-maa-sakod-alist))
 ("hleu" (["0(1KV1E(B"] . lrt-maa-sakod-alist))
 ("hlur" (["0(1KW1E(B"] . lrt-maa-sakod-alist))
 ("hlu" (["0(1KX1E(B"] . lrt-maa-sakod-alist))
 ("hluu" (["0(1KY1E(B"] . lrt-maa-sakod-alist))
 ("hle" (["(1`KEP(B"] . lrt-maa-sakod-alist))
 ("hlee" (["(1`KE(B"] . lrt-maa-sakod-alist))
 ("hlae" (["(1aKEP(B"] . lrt-maa-sakod-alist))
 ("hlaa" (["(1aKE(B"] . lrt-maa-sakod-alist))
 ("hlo" (["(1bKEP(B"] . lrt-maa-sakod-alist))
 ("hloo" (["(1bKE(B"] . lrt-maa-sakod-alist))
 ("hloe" (["(1`KERP(B"] . lrt-maa-sakod-alist))
 ("hlor" (["0(1Km1E(B"] . lrt-maa-sakod-alist))
 ("hler" (["(1`0KT1E(B"] . lrt-maa-sakod-alist))
 ("hlir" (["(1`0KU1E(B"] . lrt-maa-sakod-alist))
 ("hloua" (["0(1K[1EGP(B"] . lrt-maa-sakod-alist))
 ("hlua" (["0(1K[1EG(B"] . lrt-maa-sakod-alist))
 ("hlie" (["(1`0KQ1E]P(B"] . lrt-maa-sakod-alist))
 ("hlia" (["(1`0KQ1E](B"] . lrt-maa-sakod-alist))
 ("hleua" (["(1`0KV1EM(B"] . lrt-maa-sakod-alist))
 ("hlea" (["(1`0KW1EM(B"] . lrt-maa-sakod-alist))
 ("hlai" (["(1dKE(B"] . lrt-maa-sakod-alist))
 ("hlei" (["(1cKE(B"] . lrt-maa-sakod-alist))
 ("hlow" (["(1`0K[1ER(B"] . lrt-maa-sakod-alist))
 ("hlam" (["(1KES(B"] . lrt-maa-sakod-alist))
 ("hy" "(1K-(B")
 ("hya" (["(1K-P(B"] . lrt-maa-sakod-alist))
 ("hyar" (["(1K-R(B"] . lrt-maa-sakod-alist))
 ("hyi" (["0(1KT1-(B"] . lrt-maa-sakod-alist))
 ("hyii" (["0(1KU1-(B"] . lrt-maa-sakod-alist))
 ("hyeu" (["0(1KV1-(B"] . lrt-maa-sakod-alist))
 ("hyur" (["0(1KW1-(B"] . lrt-maa-sakod-alist))
 ("hyu" (["0(1KX1-(B"] . lrt-maa-sakod-alist))
 ("hyuu" (["0(1KY1-(B"] . lrt-maa-sakod-alist))
 ("hye" (["(1`K-P(B"] . lrt-maa-sakod-alist))
 ("hyee" (["(1`K-(B"] . lrt-maa-sakod-alist))
 ("hyae" (["(1aK-P(B"] . lrt-maa-sakod-alist))
 ("hyaa" (["(1aK-(B"] . lrt-maa-sakod-alist))
 ("hyo" (["(1bK-P(B"] . lrt-maa-sakod-alist))
 ("hyoo" (["(1bK-(B"] . lrt-maa-sakod-alist))
 ("hyoe" (["(1`K-RP(B"] . lrt-maa-sakod-alist))
 ("hyor" (["0(1Km1-(B"] . lrt-maa-sakod-alist))
 ("hyer" (["(1`0KT1-(B"] . lrt-maa-sakod-alist))
 ("hyir" (["(1`0KU1-(B"] . lrt-maa-sakod-alist))
 ("hyoua" (["0(1K[1-GP(B"] . lrt-maa-sakod-alist))
 ("hyua" (["0(1K[1-G(B"] . lrt-maa-sakod-alist))
 ("hyie" (["(1`0KQ1-]P(B"] . lrt-maa-sakod-alist))
 ("hyia" (["(1`0KQ1-](B"] . lrt-maa-sakod-alist))
 ("hyeua" (["(1`0KV1-M(B"] . lrt-maa-sakod-alist))
 ("hyea" (["(1`0KW1-M(B"] . lrt-maa-sakod-alist))
 ("hyai" (["(1dK-(B"] . lrt-maa-sakod-alist))
 ("hyei" (["(1cK-(B"] . lrt-maa-sakod-alist))
 ("hyow" (["(1`0K[1-R(B"] . lrt-maa-sakod-alist))
 ("hyam" (["(1K-S(B"] . lrt-maa-sakod-alist))
 ("hn" "(1K9(B")
 ("hna" (["(1K9P(B"] . lrt-maa-sakod-alist))
 ("hnar" (["(1K9R(B"] . lrt-maa-sakod-alist))
 ("hni" (["0(1KT19(B"] . lrt-maa-sakod-alist))
 ("hnii" (["0(1KU19(B"] . lrt-maa-sakod-alist))
 ("hneu" (["0(1KV19(B"] . lrt-maa-sakod-alist))
 ("hnur" (["0(1KW19(B"] . lrt-maa-sakod-alist))
 ("hnu" (["0(1KX19(B"] . lrt-maa-sakod-alist))
 ("hnuu" (["0(1KY19(B"] . lrt-maa-sakod-alist))
 ("hne" (["(1`K9P(B"] . lrt-maa-sakod-alist))
 ("hnee" (["(1`K9(B"] . lrt-maa-sakod-alist))
 ("hnae" (["(1aK9P(B"] . lrt-maa-sakod-alist))
 ("hnaa" (["(1aK9(B"] . lrt-maa-sakod-alist))
 ("hno" (["(1bK9P(B"] . lrt-maa-sakod-alist))
 ("hnoo" (["(1bK9(B"] . lrt-maa-sakod-alist))
 ("hnoe" (["(1`K9RP(B"] . lrt-maa-sakod-alist))
 ("hnor" (["0(1Km19(B"] . lrt-maa-sakod-alist))
 ("hner" (["(1`0KT19(B"] . lrt-maa-sakod-alist))
 ("hnir" (["(1`0KU19(B"] . lrt-maa-sakod-alist))
 ("hnoua" (["0(1K[19GP(B"] . lrt-maa-sakod-alist))
 ("hnua" (["0(1K[19G(B"] . lrt-maa-sakod-alist))
 ("hnie" (["(1`0KQ19]P(B"] . lrt-maa-sakod-alist))
 ("hnia" (["(1`0KQ19](B"] . lrt-maa-sakod-alist))
 ("hneua" (["(1`0KV19M(B"] . lrt-maa-sakod-alist))
 ("hnea" (["(1`0KW19M(B"] . lrt-maa-sakod-alist))
 ("hnai" (["(1dK9(B"] . lrt-maa-sakod-alist))
 ("hnei" (["(1cK9(B"] . lrt-maa-sakod-alist))
 ("hnow" (["(1`0K[19R(B"] . lrt-maa-sakod-alist))
 ("hnam" (["(1K9S(B"] . lrt-maa-sakod-alist))
 ("hm" "(1KA(B")
 ("hma" (["(1KAP(B"] . lrt-maa-sakod-alist))
 ("hmar" (["(1KAR(B"] . lrt-maa-sakod-alist))
 ("hmi" (["0(1KT1A(B"] . lrt-maa-sakod-alist))
 ("hmii" (["0(1KU1A(B"] . lrt-maa-sakod-alist))
 ("hmeu" (["0(1KV1A(B"] . lrt-maa-sakod-alist))
 ("hmur" (["0(1KW1A(B"] . lrt-maa-sakod-alist))
 ("hmu" (["0(1KX1A(B"] . lrt-maa-sakod-alist))
 ("hmuu" (["0(1KY1A(B"] . lrt-maa-sakod-alist))
 ("hme" (["(1`KAP(B"] . lrt-maa-sakod-alist))
 ("hmee" (["(1`KA(B"] . lrt-maa-sakod-alist))
 ("hmae" (["(1aKAP(B"] . lrt-maa-sakod-alist))
 ("hmaa" (["(1aKA(B"] . lrt-maa-sakod-alist))
 ("hmo" (["(1bKAP(B"] . lrt-maa-sakod-alist))
 ("hmoo" (["(1bKA(B"] . lrt-maa-sakod-alist))
 ("hmoe" (["(1`KARP(B"] . lrt-maa-sakod-alist))
 ("hmor" (["0(1Km1A(B"] . lrt-maa-sakod-alist))
 ("hmer" (["(1`0KT1A(B"] . lrt-maa-sakod-alist))
 ("hmir" (["(1`0KU1A(B"] . lrt-maa-sakod-alist))
 ("hmoua" (["0(1K[1AGP(B"] . lrt-maa-sakod-alist))
 ("hmua" (["0(1K[1AG(B"] . lrt-maa-sakod-alist))
 ("hmie" (["(1`0KQ1A]P(B"] . lrt-maa-sakod-alist))
 ("hmia" (["(1`0KQ1A](B"] . lrt-maa-sakod-alist))
 ("hmeua" (["(1`0KV1AM(B"] . lrt-maa-sakod-alist))
 ("hmea" (["(1`0KW1AM(B"] . lrt-maa-sakod-alist))
 ("hmai" (["(1dKA(B"] . lrt-maa-sakod-alist))
 ("hmei" (["(1cKA(B"] . lrt-maa-sakod-alist))
 ("hmow" (["(1`0K[1AR(B"] . lrt-maa-sakod-alist))
 ("hmam" (["(1KAS(B"] . lrt-maa-sakod-alist))
 )
