;; Quail package `chinese-punct' generated by the command `titdic-convert'
;;	Date: Tue Sep 23 14:59:14 1997
;;	Original TIT dictionary file: Punct.tit

;;; Comment:

;; Do byte-compile this file again after any modification.

;;; Start of the header of original TIT dictionary.

;; # $Id: Punct.el,v 1.1 1997/09/28 22:07:31 steve Exp $
;; # HANZI input table for cxterm
;; # To be used by cxterm, convert me to .cit format first
;; # .cit version 1
;; ENCODE:	GB
;; MULTICHOICE:	YES
;; PROMPT:	$A::WVJdHk!K1j5c7{:E!K# (B
;; #
;; COMMENT	Copyright 1991 by Yongguang Zhang.
;; COMMENT Permission to use/modify/copy for any purpose is hereby granted.
;; COMMENT Absolutely no fee and no warranties.
;; COMMENT
;; COMMENT	use <CTRL-f> to move to the right
;; COMMENT	use <CTRL-b> to move to the left
;; # define keys
;; VALIDINPUTKEY:	"\043$%&'()*+,-./0123456789:;<=>?@[\134]^_`abcdefghijklm
;; VALIDINPUTKEY:	nopqrstuvwxyz|~
;; SELECTKEY:	1\040
;; SELECTKEY:	2
;; SELECTKEY:	3
;; SELECTKEY:	4
;; SELECTKEY:	5
;; SELECTKEY:	6
;; SELECTKEY:	7
;; SELECTKEY:	8
;; SELECTKEY:	9
;; SELECTKEY:	0
;; BACKSPACE:	\010\177
;; DELETEALL:	\015\025
;; MOVERIGHT:	\006
;; MOVELEFT:	\002
;; REPEATKEY:	\020\022
;; # the following line must not be removed
;; BEGINDICTIONARY

;;; End of the header of original TIT dictionary.

;;; Code:

(require 'quail)

(quail-define-package "chinese-punct" "Chinese-GB" "$A1j(BG"
 t
"$A::WVJdHk!K1j5c7{:E!K# (B
	Copyright 1991 by Yongguang Zhang.
 Permission to use/modify/copy for any purpose is hereby granted.
 Absolutely no fee and no warranties.

	use <CTRL-f> to move to the right
	use <CTRL-b> to move to the left
"
 '(("\C-?" . quail-delete-last-char)
   ("\C-M" . quail-abort-translation)
   ("\C-U" . quail-abort-translation)
  )  nil nil nil nil)

(quail-define-rules
;; #
("\""	"$A#"!0!1!e(B")
("\043"	"$A##(B")
("$"	"$A#$!g!i!j(B")
("%"	"$A#%!k(B")
("'"	"$A#'!.!/!d(B")
("("	"$A#(!8!:(B")
(")"	"$A#)!9!;(B")
("*"	"$A#*!A!G!D!I(B")
("+"	"$A#+!@!F!E!H(B")
(","	"$A#,!"(B")
("-"	"$A#-!%!*!+(B")
("."	"$A#.!#!$!'!-!_!`!c!Q(B")
("/"	"$A#/!B!L#\(B")
("0"	"$A#0":"D"N"X"b"n"z(B")
("1"	"$A#1"1";"E"O"Y"e"q(B")
("2"	"$A#2"2"<"F"P"Z"f"r(B")
("3"	"$A#3"3"="G"Q"["g"s(B")
("4"	"$A#4"4">"H"R"\"h"t(B")
("5"	"$A#5"5"?"I"S"]"i"u(B")
("6"	"$A#6"6"@"J"T"^"j"v(B")
("7"	"$A#7"7"A"K"U"_"k"w(B")
("8"	"$A#8"8"B"L"V"`"l"x(B")
("9"	"$A#9"9"C"M"W"a"m"y(B")
(":"	"$A#:!K(B")
("<"	"$A#<!4!6!Z!\(B")
("="	"$A#=!Y!V!T!U(B")
(">"	"$A#>!5!7![!](B")
("@"	"$A#@!Q(B")
("["	"$A#[!2!<!>#{(B")
("\134"	"$A#\#/(B")
("]"	"$A#]!3!=!?#}(B")
("^"	"$A#^!&!P(B")
("_"	"$A#_!M(B")
("`"	"$A#`!.!/(B")
("logo"	"$A!n!o!p!q!r!s!t!u!v!w!x!y!z!{!|!}!~(B")
("math"	"$A!@!A!B!C!D!E!F!G!H!I!J!K!L!M!N!O!P!Q!R!S!T!U!V!W!X!Y!Z![!\!]!^!_!`(B")
("punct"	"$A!!!"!#!$!%!&!'!(!)!*!+!,!-!.!/!0!1!2!3!4!5!6!7!8!9!:!;!<!=!>!?(B")
("symbol"	"$A!a!b!c!d!e!f!g!h!i!j!k!l!m(B")
("|"	"$A#|!,!N(B")
("~"	"$A#~!+!W!X!^(B")
)
