(custom-put 'smiley 'custom-loads '())
(custom-put 'nnmail-various 'custom-loads '("nnmail"))
(custom-put 'nnmail-procmail 'custom-loads '("nnmail"))
(custom-put 'nnmail-expire 'custom-loads '("nnmail"))
(custom-put 'nnmail-files 'custom-loads '("nnmail"))
(custom-put 'nnmail-split 'custom-loads '("nnmail"))
(custom-put 'nnmail-duplicate 'custom-loads '("nnmail"))
(custom-put 'nnmail-prepare 'custom-loads '("nnmail"))
(custom-put 'nnmail-retrieve 'custom-loads '("nnmail"))
(custom-put 'nnmail 'custom-loads '("nnmail"))
(custom-put 'message-faces 'custom-loads '("message"))
(custom-put 'message-mail 'custom-loads '("message"))
(custom-put 'message-news 'custom-loads '("message"))
(custom-put 'message-headers 'custom-loads '("message"))
(custom-put 'message-insertion 'custom-loads '("message"))
(custom-put 'message-forwarding 'custom-loads '("message"))
(custom-put 'message-interface 'custom-loads '("message"))
(custom-put 'message-sending 'custom-loads '("message"))
(custom-put 'message-buffers 'custom-loads '("message"))
(custom-put 'message-various 'custom-loads '("message"))
(custom-put 'message 'custom-loads '("message"))
(custom-put 'gnus-various 'custom-loads '("gnus-sum"))
(custom-put 'gnus-message 'custom-loads '("message"))
(custom-put 'gnus-files 'custom-loads '("gnus" "nnmail"))
(custom-put 'gnus-visual 'custom-loads '("earcon" "gnus-art" "gnus-picon" "gnus" "smiley"))
(custom-put 'gnus-score-files 'custom-loads '("gnus-score"))
(custom-put 'gnus-score-decay 'custom-loads '("gnus-score"))
(custom-put 'gnus-score-expire 'custom-loads '("gnus-kill" "gnus-score"))
(custom-put 'gnus-score-default 'custom-loads '("gnus-score" "gnus-sum"))
(custom-put 'gnus-score-adapt 'custom-loads '("gnus-score"))
(custom-put 'gnus-score-kill 'custom-loads '("gnus-kill"))
(custom-put 'gnus-score 'custom-loads '("gnus-nocem" "gnus"))
(custom-put 'gnus-summary-tree 'custom-loads '("gnus-salt"))
(custom-put 'gnus-summary-pick 'custom-loads '("gnus-salt"))
(custom-put 'gnus-summary-various 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-visual 'custom-loads '("gnus-sum" "gnus"))
(custom-put 'gnus-summary-sort 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-mail 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-maneuvering 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-choose 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-format 'custom-loads '("gnus-sum"))
(custom-put 'gnus-thread 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-marks 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary-exit 'custom-loads '("gnus-sum"))
(custom-put 'gnus-summary 'custom-loads '("gnus-sum" "gnus"))
(custom-put 'gnus-group-various 'custom-loads '("gnus-group"))
(custom-put 'gnus-group-listing 'custom-loads '("gnus-group"))
(custom-put 'gnus-group-select 'custom-loads '("gnus-sum"))
(custom-put 'gnus-group-levels 'custom-loads '("gnus-group"))
(custom-put 'gnus-group-foreign 'custom-loads '("gnus-group"))
(custom-put 'gnus-group 'custom-loads '("gnus-topic" "gnus"))
(custom-put 'gnus-start 'custom-loads '("gnus-group" "gnus-int" "gnus-start" "gnus-util" "gnus"))
(custom-put 'gnus 'custom-loads '("gnus-art" "gnus-async" "gnus-cache" "gnus-demon" "gnus-dup" "gnus-eform" "gnus-uu" "gnus-win" "gnus-xmas" "gnus" "nnmail"))
(custom-put 'gnus-xmas 'custom-loads '("gnus-xmas"))
(custom-put 'gnus-windows 'custom-loads '("gnus-win"))
(custom-put 'gnus-extract-post 'custom-loads '("gnus-uu"))
(custom-put 'gnus-extract-archive 'custom-loads '("gnus-uu"))
(custom-put 'gnus-extract-view 'custom-loads '("gnus-sum" "gnus-uu"))
(custom-put 'gnus-extract 'custom-loads '("gnus" "gnus-uu"))
(custom-put 'gnus-topic 'custom-loads '("gnus-topic"))
(custom-put 'picons 'custom-loads '("gnus-picon"))
(custom-put 'gnus-nocem 'custom-loads '("gnus-nocem"))
(custom-put 'gnus-edit-form 'custom-loads '("gnus-eform"))
(custom-put 'gnus-duplicate 'custom-loads '("gnus-dup"))
(custom-put 'gnus-demon 'custom-loads '("gnus-demon"))
(custom-put 'gnus-cite 'custom-loads '("gnus-cite"))
(custom-put 'gnus-asynchronous 'custom-loads '("gnus-async"))
(custom-put 'gnus-article-various 'custom-loads '("gnus-art" "gnus-sum"))
(custom-put 'gnus-article-buttons 'custom-loads '("gnus-art"))
(custom-put 'gnus-article-mime 'custom-loads '("gnus-art" "gnus-sum"))
(custom-put 'gnus-article-saving 'custom-loads '("gnus-art"))
(custom-put 'gnus-article-emphasis 'custom-loads '("gnus-art"))
(custom-put 'gnus-article-washing 'custom-loads '("gnus-xmas" "gnus-art"))
(custom-put 'gnus-article-headers 'custom-loads '("gnus-art" "gnus-sum"))
(custom-put 'gnus-article-signature 'custom-loads '("gnus-art"))
(custom-put 'gnus-article-highlight 'custom-loads '("gnus-art"))
(custom-put 'gnus-article-hiding 'custom-loads '("gnus-art" "gnus-sum"))
(custom-put 'gnus-article 'custom-loads '("gnus-art" "gnus-cite"))
(custom-put 'earcon 'custom-loads '("earcon"))
