(put 'gnus-start 'custom-loads '("gnus-group" "gnus-int" "gnus-start" "gnus-util" "gnus"))
(put 'message 'custom-loads '("message"))
(put 'copyright 'custom-loads '())
(put 'gnus-score-expire 'custom-loads '("gnus-kill" "gnus-score"))
(put 'gnus-score-kill 'custom-loads '("gnus-kill"))
(put 'eldoc 'custom-loads '())
(put 'execute 'custom-loads '())
(put 'gnus-message 'custom-loads '("message"))
(put 'mouse 'custom-loads '())
(put 'mail-abbrevs 'custom-loads '())
(put 'gnus-summary-sort 'custom-loads '("gnus-sum"))
(put 'nnmail-procmail 'custom-loads '("nnmail"))
(put 'etags 'custom-loads '())
(put 'limits 'custom-loads '())
(put 'minibuffer 'custom-loads '())
(put 'environment 'custom-loads '())
(put 'sound 'custom-loads '())
(put 'gnus-article-buttons 'custom-loads '("gnus-art"))
(put 'gnus-extract-archive 'custom-loads '("gnus-uu"))
(put 'gnus-article-headers 'custom-loads '("gnus-art" "gnus-sum"))
(put 'holidays 'custom-loads '())
(put 'gnus-score 'custom-loads '("gnus-nocem" "gnus"))
(put 'gnus-summary-various 'custom-loads '("gnus-sum"))
(put 'gnus-topic 'custom-loads '("gnus-topic"))
(put 'gnus-article-emphasis 'custom-loads '("gnus-art"))
(put 'earcon 'custom-loads '("earcon"))
(put 'auto-save 'custom-loads '())
(put 'gnus-group-foreign 'custom-loads '("gnus-group"))
(put 'gnus-article-washing 'custom-loads '("gnus-xmas" "gnus-art"))
(put 'ispell 'custom-loads '())
(put 'mail 'custom-loads '("gnus" "message"))
(put 'gnus-summary-exit 'custom-loads '("gnus-sum"))
(put 'fortran-indent 'custom-loads '())
(put 'gnus-article-saving 'custom-loads '("gnus-art"))
(put 'gnus-extract-view 'custom-loads '("gnus-sum" "gnus-uu"))
(put 'gnus-group-listing 'custom-loads '("gnus-group"))
(put 'lpr 'custom-loads '())
(put 'gnus-summary 'custom-loads '("gnus-sum" "gnus"))
(put 'message-headers 'custom-loads '("message"))
(put 'editing-basics 'custom-loads '())
(put 'gnus-group-select 'custom-loads '("gnus-sum"))
(put 'internal 'custom-loads '())
(put 'calendar 'custom-loads '())
(put 'help-appearance 'custom-loads '())
(put 'display-time 'custom-loads '())
(put 'lisp 'custom-loads '())
(put 'diff 'custom-loads '())
(put 'gnus-summary-mail 'custom-loads '("gnus-sum"))
(put 'gnus-score-default 'custom-loads '("gnus-score" "gnus-sum"))
(put 'nnmail-expire 'custom-loads '("nnmail"))
(put 'gnus-thread 'custom-loads '("gnus-sum"))
(put 'gnus-nocem 'custom-loads '("gnus-nocem"))
(put 'gnus-threading 'custom-loads '("gnus-sum"))
(put 'paren-matching 'custom-loads '())
(put 'gnus-summary-maneuvering 'custom-loads '("gnus-sum"))
(put 'gnus-extract 'custom-loads '("gnus" "gnus-uu"))
(put 'help 'custom-loads '())
(put 'local 'custom-loads '())
(put 'nnmail-split 'custom-loads '("nnmail"))
(put 'keyboard 'custom-loads '())
(put 'minubuffer 'custom-loads '())
(put 'gnus-article-various 'custom-loads '("gnus-art" "gnus-sum"))
(put 'message-sending 'custom-loads '("message"))
(put 'data 'custom-loads '())
(put 'gnus-article 'custom-loads '("gnus-art" "gnus-cite"))
(put 'ps-print 'custom-loads '())
(put 'gnus 'custom-loads '("gnus-art" "gnus-async" "gnus-cache" "gnus-demon" "gnus-dup" "gnus-eform" "gnus-uu" "gnus-win" "gnus-xmas" "gnus" "nnmail"))
(put 'backup 'custom-loads '())
(put 'gnus-xmas 'custom-loads '("gnus-xmas"))
(put 'gnus-treading 'custom-loads '("gnus-sum"))
(put 'frames 'custom-loads '())
(put 'nnmail 'custom-loads '("nnmail"))
(put 'gnus-article-hiding 'custom-loads '("gnus-art" "gnus-sum"))
(put 'customize 'custom-loads '())
(put 'nnmail-duplicate 'custom-loads '("nnmail"))
(put 'gnus-summary-visual 'custom-loads '("gnus-sum" "gnus"))
(put 'gnus-group-various 'custom-loads '("gnus-group"))
(put 'abbrev 'custom-loads '())
(put 'nnmail-retrieve 'custom-loads '("nnmail"))
(put 'message-interface 'custom-loads '("message"))
(put 'gnus-group 'custom-loads '("gnus-topic" "gnus"))
(put 'gnus-article-signature 'custom-loads '("gnus-art"))
(put 'toolbar 'custom-loads '())
(put 'compilation 'custom-loads '())
(put 'dired 'custom-loads '())
(put 'gnus-duplicate 'custom-loads '("gnus-dup"))
(put 'gnus-score-adapt 'custom-loads '("gnus-score"))
(put 'nnmail-various 'custom-loads '("nnmail"))
(put 'nnmail-files 'custom-loads '("nnmail"))
(put 'gnus-asynchronous 'custom-loads '("gnus-async"))
(put 'gnus-visual 'custom-loads '("earcon" "gnus-art" "gnus-picon" "gnus" "smiley"))
(put 'message-forwarding 'custom-loads '("message"))
(put 'killing 'custom-loads '())
(put 'message-news 'custom-loads '("message"))
(put 'paren-blinking 'custom-loads '())
(put 'find-file 'custom-loads '())
(put 'gnus-edit-form 'custom-loads '("gnus-eform"))
(put 'gnus-files 'custom-loads '("gnus" "nnmail"))
(put 'gnus-cite 'custom-loads '("gnus-cite"))
(put 'gnus-demon 'custom-loads '("gnus-demon"))
(put 'gnus-summary-choose 'custom-loads '("gnus-sum"))
(put 'gnuserv 'custom-loads '())
(put 'gnus-windows 'custom-loads '("gnus-win"))
(put 'maint 'custom-loads '())
(put 'fill-comments 'custom-loads '())
(put 'message-mail 'custom-loads '("message"))
(put 'windows 'custom-loads '())
(put 'message-various 'custom-loads '("message"))
(put 'resize-minibuffer 'custom-loads '())
(put 'gnus-group-levels 'custom-loads '("gnus-group"))
(put 'gnus-summary-format 'custom-loads '("gnus-sum"))
(put 'gnus-score-decay 'custom-loads '("gnus-score"))
(put 'fill 'custom-loads '())
(put 'gnus-extract-post 'custom-loads '("gnus-uu"))
(put 'debug 'custom-loads '())
(put 'display 'custom-loads '())
(put 'faces 'custom-loads '("gnus" "message"))
(put 'diary 'custom-loads '())
(put 'gnus-various 'custom-loads '("gnus-sum"))
(put 'smiley 'custom-loads '())
(put 'browse-url 'custom-loads '())
(put 'gnus-article-highlight 'custom-loads '("gnus-art"))
(put 'news 'custom-loads '("gnus" "message"))
(put 'gnus-cache 'custom-loads '())
(put 'message-insertion 'custom-loads '("message"))
(put 'hyper-apropos 'custom-loads '())
(put 'message-faces 'custom-loads '("message"))
(put 'vc 'custom-loads '())
(put 'alloc 'custom-loads '())
(put 'isearch 'custom-loads '())
(put 'gnus-score-files 'custom-loads '("gnus-score"))
(put 'modeline 'custom-loads '())
(put 'gnus-summary-marks 'custom-loads '("gnus-sum"))
(put 'picons 'custom-loads '("gnus-picon"))
(put 'processes-basics 'custom-loads '())
(put 'nnmail-prepare 'custom-loads '("nnmail"))
(put 'message-buffers 'custom-loads '("message"))
(put 'editing 'custom-loads '())
(put 'matching 'custom-loads '())
(put 'gnus-article-mime 'custom-loads '("gnus-art" "gnus-sum"))
(put 'ps-print-color 'custom-loads '())
(put 'undo 'custom-loads '())
(put 'x 'custom-loads '())
