/* This file was automatically generated by ../lisp/gtk-marshal.el */
/* DO NOT EDIT BY HAND!!! */
#define GTK_VALUE_ARRAY(x) GTK_VALUE_POINTER(x)

#define GTK_VALUE_LIST(x) GTK_VALUE_POINTER(x)


static void
emacs_gtk_marshal_BOOL__OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[3], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_POINTER (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_STRING (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[1], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_BOOL__POINTER_BOOL (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_boolean (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__POINTER (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[1], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_BOOL__NONE (ffi_actual_function func, GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[0], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_FLOAT__OBJECT_FLOAT (ffi_actual_function func, GValue *args)
{
  __FLOAT_fn rfunc = (__FLOAT_fn) func;

  g_value_init (&args[2], G_TYPE_FLOAT);
  g_value_set_float (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1])));
}

static void
emacs_gtk_marshal_FLOAT__OBJECT (ffi_actual_function func, GValue *args)
{
  __FLOAT_fn rfunc = (__FLOAT_fn) func;

  g_value_init (&args[1], G_TYPE_FLOAT);
  g_value_set_float (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_INT__BOOL (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_boolean (&args[0])));
}

static void
emacs_gtk_marshal_INT__INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_INT__INT_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_ARRAY (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT_ARRAY (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_pointer (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT_STRING (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_POINTER_INT_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[4], G_TYPE_INT);
  g_value_set_int (&args[4],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3])));
}

static void
emacs_gtk_marshal_INT__OBJECT_POINTER_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_POINTER (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_STRING (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_INT__POINTER_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_INT__POINTER_STRING_INT (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_INT__POINTER_STRING_STRING (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2])));
}

static void
emacs_gtk_marshal_INT__POINTER_STRING (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_INT__POINTER (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_INT__STRING_STRING_INT_ARRAY (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[4], G_TYPE_INT);
  g_value_set_int (&args[4],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3])));
}

static void
emacs_gtk_marshal_INT__STRING (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_string (&args[0])));
}

static void
emacs_gtk_marshal_INT__NONE (ffi_actual_function func, GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[0], G_TYPE_INT);
  g_value_set_int (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_LIST__OBJECT (ffi_actual_function func, GValue *args)
{
  __LIST_fn rfunc = (__LIST_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_LIST__NONE (ffi_actual_function func, GValue *args)
{
  __LIST_fn rfunc = (__LIST_fn) func;

  g_value_init (&args[0], G_TYPE_POINTER);
  g_value_set_pointer (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_NONE__BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_boolean (&args[0]));
}

static void
emacs_gtk_marshal_NONE__INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]));
}

static void
emacs_gtk_marshal_NONE__INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_int (&args[0]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_BOOL_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_boolean (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_boolean (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_boolean (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_boolean (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_boolean (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_float (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]),
      g_value_get_pointer (&args[7]),
      g_value_get_pointer (&args[8]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING_INT_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_OBJECT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_object (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_pointer (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_LIST_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_LIST (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_boolean (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_boolean (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_boolean (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_FLOAT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]),
      g_value_get_int (&args[8]),
      g_value_get_int (&args[9]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_object (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_object (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_POINTER_POINTER_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_pointer (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_INT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_string (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_string (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_boolean (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING_INT_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_INT_INT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]),
      g_value_get_int (&args[8]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER_STRING_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_string (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_STRING_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_pointer (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]),
      g_value_get_pointer (&args[7]),
      g_value_get_boolean (&args[8]),
      g_value_get_boolean (&args[9]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_boolean (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]));
}

static void
emacs_gtk_marshal_NONE__POINTER_BOOL (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_boolean (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__POINTER_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_int (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]),
      g_value_get_int (&args[8]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING_INT (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_string (&args[5]),
      g_value_get_int (&args[6]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_string (&args[5]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER_STRING_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__POINTER_STRING (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]));
}

static void
emacs_gtk_marshal_NONE__NONE (ffi_actual_function func, GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) ();
}

static void
emacs_gtk_marshal_OBJECT__BOOL_BOOL_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_boolean (&args[0]),
      g_value_get_boolean (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__BOOL_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_boolean (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[6], G_TYPE_OBJECT);
  g_value_set_object (&args[6],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]),
      g_value_get_float (&args[5])));
}

static void
emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[5], G_TYPE_OBJECT);
  g_value_set_object (&args[5],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4])));
}

static void
emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[4], G_TYPE_OBJECT);
  g_value_set_object (&args[4],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3])));
}

static void
emacs_gtk_marshal_OBJECT__INT_ARRAY (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__INT_BOOL_BOOL (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_boolean (&args[1]),
      g_value_get_boolean (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT_ARRAY (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_pointer (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT_BOOL (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_boolean (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT_STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_FLOAT_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_OBJECT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[7], G_TYPE_OBJECT);
  g_value_set_object (&args[7],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[6], G_TYPE_OBJECT);
  g_value_set_object (&args[6],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[4], G_TYPE_OBJECT);
  g_value_set_object (&args[4],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__POINTER_STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__POINTER (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_FLOAT_FLOAT_FLOAT_BOOL (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[5], G_TYPE_OBJECT);
  g_value_set_object (&args[5],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_boolean (&args[4])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_INT_STRING_STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[4], G_TYPE_OBJECT);
  g_value_set_object (&args[4],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_string (&args[3])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_OBJECT (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_STRING_STRING_ARRAY_STRING_STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[6], G_TYPE_OBJECT);
  g_value_set_object (&args[6],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_string (&args[4]),
      g_value_get_string (&args[5])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__STRING (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_string (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__NONE (ffi_actual_function func, GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[0], G_TYPE_OBJECT);
  g_value_set_object (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_POINTER__BOOL_INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_boolean (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__INT_INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_INT_INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[3], G_TYPE_POINTER);
  g_value_set_pointer (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_POINTER_INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[3], G_TYPE_POINTER);
  g_value_set_pointer (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_POINTER_POINTER_ARRAY_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[11], G_TYPE_POINTER);
  g_value_set_pointer (&args[11],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]),
      g_value_get_pointer (&args[7]),
      g_value_get_pointer (&args[8]),
      g_value_get_boolean (&args[9]),
      g_value_get_boolean (&args[10])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_POINTER (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__POINTER (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__STRING (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_string (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__STRING_INT (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__NONE (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[0], G_TYPE_POINTER);
  g_value_set_pointer (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_POINTER__POINTER_POINTER (ffi_actual_function func, GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_STRING__INT_INT_INT (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[3], G_TYPE_STRING);
  g_value_set_string (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_STRING__INT (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[1], G_TYPE_STRING);
  g_value_set_string (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_BOOL (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_boolean (&args[1])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_FLOAT (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_INT_INT (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[3], G_TYPE_STRING);
  g_value_set_string (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_INT (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_STRING__OBJECT (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[1], G_TYPE_STRING);
  g_value_set_string (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_STRING__POINTER_STRING (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_STRING__POINTER (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[1], G_TYPE_STRING);
  g_value_set_string (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_STRING__NONE (ffi_actual_function func, GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[0], G_TYPE_STRING);
  g_value_set_string (&args[0],
    (*rfunc) ());
}


#include "hash.h"

static struct hash_table *marshaller_hashtable;

static void initialize_marshaller_storage (void)
{
	if (!marshaller_hashtable)
	{
		marshaller_hashtable = make_string_hash_table (200);
		puthash ("emacs_gtk_marshal_BOOL__OBJECT_INT", (void *) emacs_gtk_marshal_BOOL__OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__OBJECT_OBJECT_OBJECT", (void *) emacs_gtk_marshal_BOOL__OBJECT_OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__OBJECT_OBJECT", (void *) emacs_gtk_marshal_BOOL__OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__OBJECT_POINTER", (void *) emacs_gtk_marshal_BOOL__OBJECT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__OBJECT_STRING", (void *) emacs_gtk_marshal_BOOL__OBJECT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__OBJECT", (void *) emacs_gtk_marshal_BOOL__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__POINTER_BOOL", (void *) emacs_gtk_marshal_BOOL__POINTER_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__POINTER", (void *) emacs_gtk_marshal_BOOL__POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_BOOL__NONE", (void *) emacs_gtk_marshal_BOOL__NONE, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_FLOAT__OBJECT_FLOAT", (void *) emacs_gtk_marshal_FLOAT__OBJECT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_FLOAT__OBJECT", (void *) emacs_gtk_marshal_FLOAT__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__BOOL", (void *) emacs_gtk_marshal_INT__BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__INT", (void *) emacs_gtk_marshal_INT__INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__INT_INT", (void *) emacs_gtk_marshal_INT__INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_ARRAY", (void *) emacs_gtk_marshal_INT__OBJECT_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_INT_ARRAY", (void *) emacs_gtk_marshal_INT__OBJECT_INT_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_INT_INT", (void *) emacs_gtk_marshal_INT__OBJECT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_INT_STRING", (void *) emacs_gtk_marshal_INT__OBJECT_INT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_INT", (void *) emacs_gtk_marshal_INT__OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_OBJECT", (void *) emacs_gtk_marshal_INT__OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_POINTER_INT_INT", (void *) emacs_gtk_marshal_INT__OBJECT_POINTER_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_POINTER_INT", (void *) emacs_gtk_marshal_INT__OBJECT_POINTER_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_POINTER", (void *) emacs_gtk_marshal_INT__OBJECT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT_STRING", (void *) emacs_gtk_marshal_INT__OBJECT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__OBJECT", (void *) emacs_gtk_marshal_INT__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__POINTER_INT", (void *) emacs_gtk_marshal_INT__POINTER_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__POINTER_STRING_INT", (void *) emacs_gtk_marshal_INT__POINTER_STRING_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__POINTER_STRING_STRING", (void *) emacs_gtk_marshal_INT__POINTER_STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__POINTER_STRING", (void *) emacs_gtk_marshal_INT__POINTER_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__POINTER", (void *) emacs_gtk_marshal_INT__POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__STRING_STRING_INT_ARRAY", (void *) emacs_gtk_marshal_INT__STRING_STRING_INT_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__STRING", (void *) emacs_gtk_marshal_INT__STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_INT__NONE", (void *) emacs_gtk_marshal_INT__NONE, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_LIST__OBJECT", (void *) emacs_gtk_marshal_LIST__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_LIST__NONE", (void *) emacs_gtk_marshal_LIST__NONE, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__BOOL", (void *) emacs_gtk_marshal_NONE__BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__INT_INT", (void *) emacs_gtk_marshal_NONE__INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__INT", (void *) emacs_gtk_marshal_NONE__INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_BOOL_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_BOOL_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING_INT_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING_INT_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_OBJECT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_INT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_LIST_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_LIST_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_LIST", (void *) emacs_gtk_marshal_NONE__OBJECT_LIST, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_FLOAT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_FLOAT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_POINTER_POINTER_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_POINTER_POINTER_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_INT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_INT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_OBJECT", (void *) emacs_gtk_marshal_NONE__OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING_INT_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING_INT_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_INT_INT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_INT_INT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER_STRING_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER_STRING_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER_STRING_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER_STRING_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_POINTER", (void *) emacs_gtk_marshal_NONE__OBJECT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_STRING_BOOL", (void *) emacs_gtk_marshal_NONE__OBJECT_STRING_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_STRING_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_STRING_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT", (void *) emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_STRING_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT_STRING", (void *) emacs_gtk_marshal_NONE__OBJECT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__OBJECT", (void *) emacs_gtk_marshal_NONE__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_BOOL", (void *) emacs_gtk_marshal_NONE__POINTER_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_INT_INT", (void *) emacs_gtk_marshal_NONE__POINTER_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_INT", (void *) emacs_gtk_marshal_NONE__POINTER_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT_INT_INT", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING_INT", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_POINTER", (void *) emacs_gtk_marshal_NONE__POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_STRING_STRING", (void *) emacs_gtk_marshal_NONE__POINTER_STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER_STRING", (void *) emacs_gtk_marshal_NONE__POINTER_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__POINTER", (void *) emacs_gtk_marshal_NONE__POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_NONE__NONE", (void *) emacs_gtk_marshal_NONE__NONE, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__BOOL_BOOL_INT", (void *) emacs_gtk_marshal_OBJECT__BOOL_BOOL_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__BOOL_INT", (void *) emacs_gtk_marshal_OBJECT__BOOL_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT", (void *) emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT_ARRAY", (void *) emacs_gtk_marshal_OBJECT__INT_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT_BOOL_BOOL", (void *) emacs_gtk_marshal_OBJECT__INT_BOOL_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT_INT_ARRAY", (void *) emacs_gtk_marshal_OBJECT__INT_INT_ARRAY, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT_INT_BOOL", (void *) emacs_gtk_marshal_OBJECT__INT_INT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT_INT_STRING", (void *) emacs_gtk_marshal_OBJECT__INT_INT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT_INT", (void *) emacs_gtk_marshal_OBJECT__INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__INT", (void *) emacs_gtk_marshal_OBJECT__INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_FLOAT_INT", (void *) emacs_gtk_marshal_OBJECT__OBJECT_FLOAT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_INT", (void *) emacs_gtk_marshal_OBJECT__OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_OBJECT", (void *) emacs_gtk_marshal_OBJECT__OBJECT_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT_INT", (void *) emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT", (void *) emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT", (void *) emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT_STRING", (void *) emacs_gtk_marshal_OBJECT__OBJECT_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__OBJECT", (void *) emacs_gtk_marshal_OBJECT__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__POINTER_POINTER", (void *) emacs_gtk_marshal_OBJECT__POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__POINTER_STRING", (void *) emacs_gtk_marshal_OBJECT__POINTER_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__POINTER", (void *) emacs_gtk_marshal_OBJECT__POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__STRING_FLOAT_FLOAT_FLOAT_BOOL", (void *) emacs_gtk_marshal_OBJECT__STRING_FLOAT_FLOAT_FLOAT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__STRING_INT_STRING_STRING", (void *) emacs_gtk_marshal_OBJECT__STRING_INT_STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__STRING_OBJECT", (void *) emacs_gtk_marshal_OBJECT__STRING_OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__STRING_STRING_STRING_ARRAY_STRING_STRING", (void *) emacs_gtk_marshal_OBJECT__STRING_STRING_STRING_ARRAY_STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__STRING_STRING", (void *) emacs_gtk_marshal_OBJECT__STRING_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__STRING", (void *) emacs_gtk_marshal_OBJECT__STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_OBJECT__NONE", (void *) emacs_gtk_marshal_OBJECT__NONE, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__BOOL_INT", (void *) emacs_gtk_marshal_POINTER__BOOL_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__INT_INT", (void *) emacs_gtk_marshal_POINTER__INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__INT", (void *) emacs_gtk_marshal_POINTER__INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__OBJECT_INT_INT", (void *) emacs_gtk_marshal_POINTER__OBJECT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__OBJECT_INT", (void *) emacs_gtk_marshal_POINTER__OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__OBJECT_POINTER_INT", (void *) emacs_gtk_marshal_POINTER__OBJECT_POINTER_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__OBJECT_POINTER_POINTER_ARRAY_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL", (void *) emacs_gtk_marshal_POINTER__OBJECT_POINTER_POINTER_ARRAY_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__OBJECT_POINTER", (void *) emacs_gtk_marshal_POINTER__OBJECT_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__OBJECT", (void *) emacs_gtk_marshal_POINTER__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__POINTER", (void *) emacs_gtk_marshal_POINTER__POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__STRING", (void *) emacs_gtk_marshal_POINTER__STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__STRING_INT", (void *) emacs_gtk_marshal_POINTER__STRING_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__NONE", (void *) emacs_gtk_marshal_POINTER__NONE, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_POINTER__POINTER_POINTER", (void *) emacs_gtk_marshal_POINTER__POINTER_POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__INT_INT_INT", (void *) emacs_gtk_marshal_STRING__INT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__INT", (void *) emacs_gtk_marshal_STRING__INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__OBJECT_BOOL", (void *) emacs_gtk_marshal_STRING__OBJECT_BOOL, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__OBJECT_FLOAT", (void *) emacs_gtk_marshal_STRING__OBJECT_FLOAT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__OBJECT_INT_INT", (void *) emacs_gtk_marshal_STRING__OBJECT_INT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__OBJECT_INT", (void *) emacs_gtk_marshal_STRING__OBJECT_INT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__OBJECT", (void *) emacs_gtk_marshal_STRING__OBJECT, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__POINTER_STRING", (void *) emacs_gtk_marshal_STRING__POINTER_STRING, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__POINTER", (void *) emacs_gtk_marshal_STRING__POINTER, marshaller_hashtable);
		puthash ("emacs_gtk_marshal_STRING__NONE", (void *) emacs_gtk_marshal_STRING__NONE, marshaller_hashtable);
	};
}

static void *find_marshaller (const char *func_name)
{
	void *fn = NULL;
	initialize_marshaller_storage ();

	if (gethash (func_name, marshaller_hashtable, (const void **)&fn))
	{
		return (fn);
	}

	return (NULL);
}
