;;; custom-load.el --- automatically extracted custom dependencies


;;; Code:

(custom-add-loads 'message '("sendmail"))
(custom-add-loads 'prolog '("prolog"))
(custom-add-loads 'mouse '("outl-mouse"))
(custom-add-loads 'mail-abbrevs '("mail-abbrevs"))
(custom-add-loads 'pascal '("pascal"))
(custom-add-loads 'tex '("reftex" "texinfo"))
(custom-add-loads 'icon '("icon"))
(custom-add-loads 'texinfo '("texinfo"))
(custom-add-loads 'mail '("mail-abbrevs"))
(custom-add-loads 'docs '("texinfo"))
(custom-add-loads 'lisp-indent '("cl-indent"))
(custom-add-loads 'tools '("hideshow" "lazy-shot" "make-mode"))
(custom-add-loads 'lisp '("cl-indent"))
(custom-add-loads 'reftex '("reftex"))
(custom-add-loads 'outlines '("hideshow" "outl-mouse"))
(custom-add-loads 'perl '("cperl-mode"))
(custom-add-loads 'reftex-label-support '("reftex"))
(custom-add-loads 'outl-mouse '("outl-mouse"))
(custom-add-loads 'frames '("rsz-minibuf"))
(custom-add-loads 'cperl-electric '("cperl-mode"))
(custom-add-loads 'lazy-shot '("lazy-shot"))
(custom-add-loads 'scribe '("scribe"))
(custom-add-loads 'c-macro '("cmacexp"))
(custom-add-loads 'cperl-faces '("cperl-mode"))
(custom-add-loads 'resize-minibuffer '("rsz-minibuf"))
(custom-add-loads 'languages '("cperl-mode" "icon" "pascal" "prolog" "rexx-mode" "vhdl-mode"))
(custom-add-loads 'cperl-indent '("cperl-mode"))
(custom-add-loads 'faces '("cperl-mode" "lazy-shot"))
(custom-add-loads 'hideshow '("hideshow"))
(custom-add-loads 'vhdl '("vhdl-mode"))
(custom-add-loads 'enriched '("enriched"))
(custom-add-loads 'processes '("executable"))
(custom-add-loads 'rexx '("rexx-mode"))
(custom-add-loads 'executable '("executable"))
(custom-add-loads 'wp '("enriched" "scribe" "texinfo"))
(custom-add-loads 'makefile-mode '("make-mode"))
(custom-add-loads 'c '("cmacexp"))

;;; custom-load.el ends here
