(custom-put 'extensions 'custom-loads '(("auto-show") "strokes"))
(custom-put 'mouse 'custom-loads '("strokes"))
(custom-put 'environment 'custom-loads '(("rsz-minibuf")))
(custom-put 'lisp 'custom-loads '("strokes"))
(custom-put 'strokes 'custom-loads '("strokes"))
(custom-put 'display 'custom-loads '(("auto-show")))
