(custom-put 'ediff 'custom-loads '("ediff-diff" "ediff-merg" "ediff-mult" "ediff-ptch" "ediff-wind" "ediff" "ediff-init"))
(custom-put 'ediff-window 'custom-loads '())
(custom-put 'ediff-ptch 'custom-loads '("ediff-ptch"))
(custom-put 'ediff-mult 'custom-loads '("ediff-mult"))
(custom-put 'ediff-merge 'custom-loads '("ediff-merg"))
(custom-put 'ediff-diff 'custom-loads '("ediff-diff"))
