(custom-put 'environment 'custom-loads '(("ediff-wind")))
(custom-put 'tools 'custom-loads '("ediff"))
(custom-put 'ediff-diff 'custom-loads '("ediff-diff"))
(custom-put 'frames 'custom-loads '("ediff-wind"))
(custom-put 'ediff-ptch 'custom-loads '("ediff-ptch"))
(custom-put 'ediff-merge 'custom-loads '("ediff-merg"))
(custom-put 'ediff-mult 'custom-loads '("ediff-mult"))
(custom-put 'ediff 'custom-loads '("ediff-diff" "ediff-init" "ediff-merg" "ediff-mult" "ediff-ptch" "ediff-wind" "ediff"))
